const juegos = [
    {
        consola: "NES",
        lista: [
            "Mega Man 3",
            "The Legend of Zelda",
            "Super Mario Bros. 3",
            "Little Samson",
            "Mike Tyson's Punch-Out!!",
            "Bucky O'Hare",
            "Double Dragon II: The Revenge",
            "Teenage Mutant Ninja Turtles III: The Manhattan Project",
            "Batman: The Video Game",
            "Vice: Project Doom",
            "Jackal",
            "Kyattou Ninden Teyandee (Samurai Pizza Cats)",
            "Disney's Chip 'n Dale: Rescue Rangers",
            "Solstice: The Quest for the Staff of Demnos",
            "Mitsume ga Tōru",
            "Blaster Master",
            "Bomberman II",
            "Gauntlet"
        ]
    
    },
    {
        consola: "SNES",
        lista: [
            "Super Metroid",
            "Super Mario All-Stars (Super Mario Bros. 3)",
            "Super Castlevania IV (Versión Japonesa)",
            "Final Fantasy III",
            "Wild Guns",
            "EarthBound",
            "Ganbare Goemon 2: Kiteretsu Shogun Magginesu",
            "Secret of Mana (Seiken Densetsu 2)",
            "Super Mario RPG: Legend of the Seven Stars",
            "Terranigma",
            "Equinox",
            "Demon's Crest",
            "Ogre Battle: The March of the Black Queen",
            "Cybernator",
            "Skyblazer"
        ]
    
    },
    {
        consola: "SEGA Mega Drive",
        lista: [
            "Ristar",
            "Streets of Rage",
            "Sonic & Knuckles",
            "Castle of Illusion Starring Mickey Mouse",
            "Shinobi III: Return of the Ninja Master",
            "Earthworm Jim 2",
            "Flashback: The Quest for Identity",
            "Tiny Toon Adventures: Buster's Hidden Treasure",
            "Landstalker",
            "Alien Soldier",
            "Monster World IV",
            "Jungle Strike",
            "Disney's The Jungle Book",
            "Strider",
            "Castlevania: Bloodlines"
        ]
    
    },
    {
        consola: "Game Boy",
        lista: [
            "The Legend of Zelda: Link's Awakening",
            "Kid Dracula (GB)",
            "Final Fantasy Adventure",
            "The Smurfs",
            "Super Mario Land 2: 6 Golden Coins",
            "Mole Mania",
            "Monster Max",
            "Kirby’s Dream Land 2",
            "Tiny Toon Adventures: Babs' Big Break",
            "Gargoyle's Quest",
            "Ikari Warriors (o Avenging Spirit)",
            "Samurai Shodown",
            "Amazing Tater",
            "Track & Field",
            "Alfred Chicken"
        ]
    
    },
    {
        consola: "PlayStation",
        lista: [
            "Final Fantasy IX",
            "Suikoden",
            "Silent Hill",
            "Crash Bandicoot 2: Cortex Strikes Back",
            "Alone in the Dark 2",
            "Driver 2: Back on the Streets",
            "Crash Team Racing",
            "Dino Crisis",
            "Syphon Filter 2",
            "Fear Effect",
            "Heart of Darkness",
            "Pac-Man World",
            "Legacy of Kain: Soul Reaver",
            "Vagrant Story",
            "Spyro: Year of the Dragon",
            "Koudelka",
            "Galerians"
        ]
    
    },
    {
        consola: "Nintendo 64",
        lista: [
            "Paper Mario",
            "GoldenEye 007",
            "Banjo-Kazooie",
            "Conker's Bad Fur Day",
            "Ogre Battle 64: Person of Lordly Caliber",
            "Diddy Kong Racing",
            "Donkey Kong 64",
            "Turok 2: Seeds of Evil",
            "Star Wars: Rogue Squadron",
            "Blast Corps",
            "Sin and Punishment",
            "Excitebike 64",
            "Shadow Man"
        ]
    
    },
    {
        consola: "Game Boy Color",
        lista: [
            "Crystalis",
            "Walt Disney's The Jungle Book: Mowgli's Wild Adventure",
            "Magi Nation",
            "Dragonyhm",
            "The Legend of Zelda: Link's Awakening DX",
            "Metal Gear Solid (o Metal Gear Ghost Babel)",
            "Mario Tennis",
            "Wario Land 3",
            "Dragon Quest Monsters",
            "Warlock",
            "Survival Kids",
            "Looney Tunes: Marvin Strikes Back!",
            "Shantae",
            "Tomb Raider Starring Lara Croft",
            "Spy vs. Spy"
        ]
    
    },
    {
        consola: "PlayStation 2",
        lista: [
            "Kingdom Hearts",
            "Final Fantasy X",
            "Spyro: Enter the Dragonfly (o el que juegues de la saga en PS2)",
            "Sly 2: Band of Thieves",
            "Evil Dead: Regeneration",
            "Ōkami",
            "Silent Hill 2",
            "God of War",
            "Metal Gear Solid 2: Sons of Liberty",
            "Ico",
            "Jak and Daxter: The Precursor Legacy",
            "Ratchet & Clank",
            "Katamari Damacy",
            "Tekken 5",
            "Disgaea: Hour of Darkness",
            "The Warriors",
            "LEGO Indiana Jones: The Original Adventures",
            "Devil May Cry",
            "Grand Theft Auto III",
            "Def Jam: Fight for NY",
            "WWE SmackDown! Here Comes the Pain",
            "The Simpsons Hit & Run",
            "Rule of Rose",
            "Haunting Ground",
            "Shin Megami Tensei: Digital Devil Saga",
            "Mortal Kombat: Shaolin Monks",
            "Downhill Domination",
            "Burnout 3: Takedown",
            "Dragon Quest VIII: Journey of the Cursed King",
            "Rogue Galaxy",
            "Dark Chronicle / Dark Cloud 2",
            "Dirge of Cerberus: Final Fantasy VII",
            "Onimusha 3: Demon Siege",
            "Shadow of Rome",
            "Urban Chaos: Riot Response",
            "Disaster Report",
            "Rise to Honor",
            "Forbidden Siren 2",
            "Gregory Horror Show",
            "Clock Tower 3",
            "Cold Fear",
            "Spider-Man 2",
            "Hulk: Ultimate Destruction",
            "The Punisher",
            "Scarface: The World Is Yours",
            "Marvel Ultimate Alliance",
            "X-Men Legends"
        ]
    
    },
    {consola: "Dreamcast",
        lista: [
            "Shenmue",
            "Resident Evil 2",
            "Sonic Adventure 2",
            "Skies of Arcadia",
            "Dead or Alive 2",
            "Jet Grind Radio (o Jet Set Radio)",
            "Guilty Gear X",
            "Marvel vs. Capcom 2: New Age of Heroes",
            "Rez",
            "MDK2",
            "Grandia II",
            "Headhunter",
            "Sturmwind (o Giga Wing)",
            "The House of the Dead 2",
            "Spider-Man"
        ]
    
    },
    {
        consola: "GameCube",
        lista: [
            "The Legend of Zelda: The Wind Waker",
            "Super Mario Sunshine",
            "Resident Evil 4",
            "Paper Mario: The Thousand-Year Door",
            "Resident Evil (Remake)",
            "Fire Emblem: Path of Radiance",
            "Metroid Prime",
            "Prince of Persia: The Sands of Time",
            "Pikmin 2",
            "Viewtiful Joe",
            "SoulCalibur II",
            "Super Smash Bros. Melee",
            "Eternal Darkness: Sanity's Requiem",
            "TimeSplitters 2",
            "Star Wars Rogue Squadron II: Rogue Leader"
        ]
    
    },
    {
        consola: "Game Boy Advance",
        lista: [
            "The Legend of Zelda: The Minish Cap",
            "Metroid Fusion",
            "Final Fantasy Tactics Advance",
            "Golden Sun: The Lost Age",
            "Mario & Luigi: Superstar Saga",
            "Wario Land 4",
            "Mother 3",
            "Tactics Ogre: The Knight of Lodis",
            "Fire Emblem: The Sacred Stones",
            "Super Robot Taisen: Original Generation 2",
            "Rhythm Tengoku",
            "Klonoa: Empire of Dreams",
            "Sonic Advance 2",
            "Shining Force: Resurrection of the Dark Dragon",
            "Castlevania: Circle of the Moon"
        ]
    
    },
    {
        consola: "Nintendo Wii",
        lista: [
            "New Super Mario Bros. Wii",
            "Super Smash Bros. Brawl",
            "Kirby's Return to Dream Land",
            "Donkey Kong Country Returns",
            "Super Mario Galaxy",
            "Xenoblade Chronicles",
            "No More Heroes",
            "Super Paper Mario",
            "Klonoa (Wii)",
            "Muramasa: The Demon Blade",
            "Transformers Prime: The Game",
            "Mega Man 9",
            "Call of Duty: Modern Warfare 3",
            "Rhythm Heaven Fever",
            "Endless Ocean: Blue World"
        ]
    
    },
    {
        consola: "Nintendo DS",
        lista: [
            "The Legend of Zelda: Phantom Hourglass",
            "New Super Mario Bros.",
            "Castlevania: Portrait of Ruin",
            "Dragon Quest V: Hand of the Heavenly Bride",
            "Grand Theft Auto: Chinatown Wars",
            "Osu! Tatakae! Ouendan!",
            "Mario & Luigi: Bowser's Inside Story",
            "Phoenix Wright: Ace Attorney - Trials and Tribulations",
            "Professor Layton and the Curious Village",
            "Jump Ultimate Stars",
            "Shin Megami Tensei: Devil Survivor",
            "Ninja Gaiden: Dragon Sword",
            "Trauma Center: Under the Knife 2",
            "Lock's Quest",
            "Sonic Colors",
            "Age of Empires: The Age of Kings",
            "Yoshi's Island DS"
        ]
    
    },
    {
        consola: "PSP",
        lista: [
            "Metal Gear Solid: Peace Walker",
            "Jeanne d'Arc",
            "Secret Agent Clank",
            "Killzone: Liberation",
            "Gurumin: A Monstrous Adventure",
            "Persona 3 Portable",
            "Tactics Ogre: Let Us Cling Together",
            "Monster Hunter Freedom Unite",
            "Kingdom Hearts: Birth by Sleep",
            "Final Fantasy Tactics: The War of the Lions",
            "Disgaea 2: Dark Hero Days",
            "Ghost Rider",
            "The Legend of Heroes: Trails in the Sky",
            "Phantasy Star Portable 2",
            "Patapon 2",
            "LittleBigPlanet",
            "Kenka Bancho: Badass Rumble",
            "Dante's Inferno",
            "Resistance: Retribution",
            "Tenchu: Shadow Assassins",
            "Silent Hill: Origins",
            "Corpse Party",
            "Class of Heroes",
            "Crisis Core: Final Fantasy VII",
            "PixelJunk Monsters Deluxe"
        ]
    
    },
    
        
    {
        consola: "PC",
        lista: [
            "Half-Life",
            "GTA San Andreas",
            "Ship of Harkinian (The Legend of Zelda: Ocarina of Time)",
            "Battlefield 1942",
            "Borderlands",
            "Naruto Shippuden: Ultimate Ninja Storm 1",
            "Naruto Shippuden: Ultimate Ninja Storm 2",
            "Dragon Ball Xenoverse",
            "Celeste",
            "Cuphead",
            "Pariah 2005",
            "Max Payne 1 (2001)",
            "Medal of Honor Allied Assault",
            "Beyond Good & Evil",
            "Doom 3",
            "F.E.A.R.",
            "The Elder Scrolls IV: Oblivion",
            "Company of Heroes",
            "Hitman: Blood Money",
            "Yakuza 0",
            "2 Ship 2 Harkinian (The Legend of Zelda: Majora's Mask)",
            "Perfect Dark (versión para PC)",
            "Batman: Arkham Asylum",
            "The Binding of Isaac: Rebirth",
            "Left 4 Dead 2",
            "Transformers: La caída de Cybertron",
            "PAC-MAN WORLD 2 Re-PAC",
            "Blasphemous 2",
            "Tomb Raider (2013)",
            "Sleeping Dogs",
            "Assassin's Creed Brotherhood",
            "Mafia II",
            "Just Cause 2",
            "Mirror's Edge",
            "Dead Space",
            "Mass Effect 1",
            "Dead Cells",
            "Dishonored",
            "Return of the Obra Dinn",
            "BioShock",
            "Shovel Knight",
            "Dragon Age: Origins",
            "Inside",
            "Call of Duty 4: Modern Warfare",
            "Deus Ex: Human Revolution",
            "Crysis",
            "Animal Well",
            "Ori and the Blind Forest: Definitive Edition",
            "Katana ZERO",
            "Rayman Legends",
            "Ōkami HD",
            "Disco Elysium",
            "Wolfenstein: The New Order",
            "Max Payne 3",
            "Metal Gear Solid V: The Phantom Pain",
            "Hi-Fi Rush",
            "Halo: The Master Chief Collection",
            "Prince of Persia: The Lost Crown",
            "Sonic Colors: Ultimate",
            "Dragon Quest I y II HD-2D Remake",
            "LEGO Marvel Super Heroes 1-2",
            "Assassin's Creed III",
            "Assassin's Creed IV: Black Flag",
            "TMNT: Shredder's Revenge",
            "Darksiders 1",
            "StarCraft II: Wings of Liberty",
            "Fallout: New Vegas",
            "Battlefield: Bad Company 2",
            "Metro 2033",
            "Limbo",
            "The Thing",
            "Peter Jackson's King Kong"
        ]
    }
];