const juegos = [
  {
    consola: "Arcade",
    lista: [
      { titulo: "Golden Axe", duracion: { principal: "1 h", extras: "1 h 15 min", completo: "1.5 h" }, anio: 1989, genero: "Beat 'em up / Fantasía", desarrolladora: "SEGA" },
      { titulo: "Strider", duracion: { principal: "1 h", extras: "2 h", completo: "3 h" }, anio: 1989, genero: "Hack and Slash / Acción", desarrolladora: "Capcom" },
      { titulo: "Ikari Warriors", duracion: { principal: "1 h", extras: "1.5 h", completo: "1.5 h" }, anio: 1986, genero: "Run and Gun", desarrolladora: "SNK" },
      { titulo: "Jackal", duracion: { principal: "55 min", extras: "1.5 h", completo: "2 h" }, anio: 1986, genero: "Run and Gun", desarrolladora: "Konami" },
      { titulo: "Rolling Thunder 2", duracion: { principal: "58 min", extras: "1 h 20 min", completo: "1.5 h" }, anio: 1990, genero: "Run and Gun / Acción", desarrolladora: "Namco" },
      { titulo: "Sunset Riders", duracion: { principal: "1 h", extras: "1.5 h", completo: "3.5 h" }, anio: 1991, genero: "Run and Gun / Western", desarrolladora: "Konami" },
      { titulo: "Time Crisis", duracion: { principal: "53 min", extras: "1 h 15 min", completo: "2.5 h" }, anio: 1995, genero: "Rail Shooter", desarrolladora: "Namco" },
      { titulo: "Shadow Warriors (Ninja Gaiden)", duracion: { principal: "45 min", extras: "1 h", completo: "3 h" }, anio: 1988, genero: "Beat 'em up / Acción", desarrolladora: "Tecmo" },
      { titulo: "Alien Storm", duracion: { principal: "51 min", extras: "2 h", completo: "3.5 h" }, anio: 1990, genero: "Beat 'em up / Ciencia Ficción", desarrolladora: "SEGA" },
      { titulo: "Blood Bros.", duracion: { principal: "37 min", extras: "2 h 11 min", completo: "2.5 h" }, anio: 1990, genero: "Shooter / Western", desarrolladora: "TAD Corporation" },
      { titulo: "The Simpsons Arcade Game", duracion: { principal: "49 min", extras: "1 h 15 min", completo: "1.5 h" }, anio: 1991, genero: "Beat 'em up", desarrolladora: "Konami" },
      { titulo: "Captain Commando", duracion: { principal: "47 min", extras: "55 min", completo: "1 h" }, anio: 1991, genero: "Beat 'em up / Ciencia Ficción", desarrolladora: "Capcom" },
      { titulo: "X-Men (1992)", duracion: { principal: "1 h", extras: "1 h 15 min", completo: "2 h" }, anio: 1992, genero: "Beat 'em up / Superhéroes", desarrolladora: "Konami" },
      { titulo: "Samurai Shodown", duracion: { principal: "1 h", extras: "2 h", completo: "6 h" }, anio: 1993, genero: "Lucha", desarrolladora: "SNK" },
      { titulo: "Shock Troopers", duracion: { principal: "1 h", extras: "2.5 h", completo: "5 h" }, anio: 1997, genero: "Run and Gun", desarrolladora: "Saurus / SNK" },
      { titulo: "Knights of the Round", duracion: { principal: "1 h", extras: "1.5 h", completo: "3 h" }, anio: 1991, genero: "Beat 'em up / Hack and Slash", desarrolladora: "Capcom" },
      { titulo: "The Punisher", duracion: { principal: "1 h", extras: "1.5 h", completo: "2.5 h" }, anio: 1993, genero: "Beat 'em up", desarrolladora: "Capcom" },
      { titulo: "The King of Dragons", duracion: { principal: "1 h", extras: "1.5 h", completo: "3 h" }, anio: 1991, genero: "Beat 'em up / Fantasía", desarrolladora: "Capcom" },
      { titulo: "Dungeons & Dragons: Tower of Doom", duracion: { principal: "1 h", extras: "2.5 h", completo: "5 h" }, anio: 1993, genero: "Beat 'em up / RPG", desarrolladora: "Capcom" },
      { titulo: "Cadillacs and Dinosaurs", duracion: { principal: "1 h", extras: "1.5 h", completo: "3 h" }, anio: 1993, genero: "Beat 'em up", desarrolladora: "Capcom" },
      { titulo: "Alien vs. Predator", duracion: { principal: "1 h", extras: "1.5 h", completo: "3.5 h" }, anio: 1994, genero: "Beat 'em up / Ciencia Ficción", desarrolladora: "Capcom" }
    ]
  },
  {
    consola: "NES",
    lista: [
      { titulo: "The Legend of Zelda", duracion: { principal: "8 h", extras: "8.5 h", completo: "9.5 h" }, anio: 1986, genero: "Acción / Aventura", desarrolladora: "Nintendo" },
      { titulo: "Little Samson", duracion: { principal: "2 h", extras: "3.5 h", completo: "4 h" }, anio: 1992, genero: "Plataformas / Acción", desarrolladora: "Taito" },
      { titulo: "Mike Tyson's Punch-Out!!", duracion: { principal: "3 h", extras: "4 h", completo: "7.5 h" }, anio: 1987, genero: "Deportes / Lucha", desarrolladora: "Nintendo" },
      { titulo: "Bucky O'Hare", duracion: { principal: "1.5 h", extras: "2 h", completo: "2.5 h" }, anio: 1992, genero: "Plataformas / Run and Gun", desarrolladora: "Konami" },
      { titulo: "Double Dragon II: The Revenge", duracion: { principal: "1 h", extras: "1.5 h", completo: "2.5 h" }, anio: 1989, genero: "Beat 'em up", desarrolladora: "Technōs Japan" },
      { titulo: "TMNT III: The Manhattan Project", duracion: { principal: "1 h", extras: "1 h", completo: "1.5 h" }, anio: 1991, genero: "Beat 'em up", desarrolladora: "Konami" },
      { titulo: "Batman: The Video Game", duracion: { principal: "1.5 h", extras: "2 h", completo: "2.5 h" }, anio: 1989, genero: "Plataformas / Acción", desarrolladora: "Sunsoft" },
      { titulo: "Vice: Project Doom", duracion: { principal: "1.5 h", extras: "1.5 h", completo: "2 h" }, anio: 1991, genero: "Acción / Plataformas", desarrolladora: "Aicom" },
      { titulo: "Kyattou Ninden Teyandee", duracion: { principal: "1 h", extras: "1 h", completo: "1.5 h" }, anio: 1991, genero: "Plataformas / Acción", desarrolladora: "Tecmo" },
      { titulo: "Disney's Chip 'n Dale: Rescue Rangers", duracion: { principal: "1 h", extras: "1 h", completo: "1.5 h" }, anio: 1990, genero: "Plataformas", desarrolladora: "Capcom" },
      { titulo: "Solstice: Quest for the Staff of Demnos", duracion: { principal: "4 h", extras: "6 h", completo: "8 h" }, anio: 1990, genero: "Puzle / Aventura", desarrolladora: "Software Creations" },
      { titulo: "Mitsume ga Tōru", duracion: { principal: "2.5 h", extras: "3 h", completo: "3 h" }, anio: 1992, genero: "Plataformas / Acción", desarrolladora: "Natsume" },
      { titulo: "Blaster Master", duracion: { principal: "3.5 h", extras: "4 h", completo: "5 h" }, anio: 1988, genero: "Plataformas / Metroidvania", desarrolladora: "Sunsoft" },
      { titulo: "Bomberman II", duracion: { principal: "2 h", extras: "2.5 h", completo: "4 h" }, anio: 1991, genero: "Puzle / Acción", desarrolladora: "Hudson Soft" },
      { titulo: "Kid Dracula", duracion: { principal: "2 h", extras: "2.5 h", completo: "3 h" }, anio: 1990, genero: "Plataformas / Comedia", desarrolladora: "Konami" },
      { titulo: "Crystalis", duracion: { principal: "10 h", extras: "12 h", completo: "14 h" }, anio: 1990, genero: "ARPG / Aventura", desarrolladora: "SNK" }
    ]
  },
  {
    consola: "SNES",
    lista: [
      { titulo: "Super Metroid", duracion: { principal: "7.5 h", extras: "9 h", completo: "10.5 h" }, anio: 1994, genero: "Metroidvania / Acción", desarrolladora: "Nintendo" },
      { titulo: "Super Castlevania IV", duracion: { principal: "3.5 h", extras: "4 h", completo: "5 h" }, anio: 1991, genero: "Plataformas / Acción", desarrolladora: "Konami" },
      { titulo: "EarthBound", duracion: { principal: "28 h", extras: "33 h", completo: "38 h" }, anio: 1994, genero: "RPG", desarrolladora: "Ape / HAL Laboratory" },
      { titulo: "Ganbare Goemon 2", duracion: { principal: "4 h", extras: "6 h", completo: "8 h" }, anio: 1993, genero: "Plataformas / Acción", desarrolladora: "Konami" },
      { titulo: "Secret of Mana", duracion: { principal: "23 h", extras: "27 h", completo: "34 h" }, anio: 1993, genero: "ARPG / Aventura", desarrolladora: "Square" },
      { titulo: "Super Mario RPG", duracion: { principal: "18 h", extras: "21 h", completo: "28 h" }, anio: 1996, genero: "RPG / Plataformas", desarrolladora: "Square / Nintendo" },
      { titulo: "Terranigma", duracion: { principal: "20 h", extras: "24 h", completo: "31 h" }, anio: 1995, genero: "ARPG", desarrolladora: "Quintet" },
      { titulo: "Equinox", duracion: { principal: "9 h", extras: "11 h", completo: "13 h" }, anio: 1993, genero: "Puzle / Aventura", desarrolladora: "Software Creations" },
      { titulo: "Demon's Crest", duracion: { principal: "3.5 h", extras: "5 h", completo: "6.5 h" }, anio: 1994, genero: "Plataformas / Acción", desarrolladora: "Capcom" },
      { titulo: "Ogre Battle: March of the Black Queen", duracion: { principal: "30 h", extras: "42 h", completo: "55 h" }, anio: 1993, genero: "Estrategia / RPG", desarrolladora: "Quest" },
      { titulo: "Cybernator", duracion: { principal: "2 h", extras: "3 h", completo: "4.5 h" }, anio: 1992, genero: "Mecha / Run and Gun", desarrolladora: "NCS Corp / Masaya" },
      { titulo: "Skyblazer", duracion: { principal: "3 h", extras: "4 h", completo: "5 h" }, anio: 1994, genero: "Plataformas / Acción", desarrolladora: "Umanosuke / Sony" },
      { titulo: "The Smurfs", duracion: { principal: "2 h", extras: "3 h", completo: "4 h" }, anio: 1994, genero: "Plataformas", desarrolladora: "Infogrames" },
      { titulo: "Alfred Chicken", duracion: { principal: "3 h", extras: "4 h", completo: "5 h" }, anio: 1993, genero: "Plataformas", desarrolladora: "Twilight" }
    ]
  },
  {
    consola: "Sega Mega Drive / Genesis",
    lista: [
      { titulo: "Ristar", duracion: { principal: "2.5 h", extras: "3 h", completo: "4.5 h" }, anio: 1995, genero: "Plataformas", desarrolladora: "Sonic Team / SEGA" },
      { titulo: "Streets of Rage", duracion: { principal: "1.5 h", extras: "2 h", completo: "3 h" }, anio: 1991, genero: "Beat 'em up", desarrolladora: "SEGA" },
      { titulo: "Sonic 3 & Knuckles", duracion: { principal: "4 h", extras: "5.5 h", completo: "7 h" }, anio: 1994, genero: "Plataformas", desarrolladora: "Sonic Team / SEGA" },
      { titulo: "Tiny Toon Adventures: Buster's Hidden Treasure", duracion: { principal: "3 h", extras: "3.5 h", completo: "4 h" }, anio: 1993, genero: "Plataformas", desarrolladora: "Konami" },
      { titulo: "Landstalker", duracion: { principal: "16 h", extras: "19 h", completo: "22.5 h" }, anio: 1992, genero: "ARPG / Aventura", desarrolladora: "Climax Entertainment" },
      { titulo: "Alien Soldier", duracion: { principal: "3 h", extras: "4 h", completo: "6 h" }, anio: 1995, genero: "Run and Gun / Acción", desarrolladora: "Treasure" },
      { titulo: "Jungle Strike", duracion: { principal: "4 h", extras: "5 h", completo: "6.5 h" }, anio: 1993, genero: "Acción / Estrategia", desarrolladora: "Electronic Arts" },
      { titulo: "Disney's The Jungle Book", duracion: { principal: "2 h", extras: "2.5 h", completo: "3 h" }, anio: 1994, genero: "Plataformas", desarrolladora: "Eurocom / Virgin Interactive" },
      { titulo: "Castlevania: Bloodlines", duracion: { principal: "2.5 h", extras: "3 h", completo: "4 h" }, anio: 1994, genero: "Plataformas / Acción", desarrolladora: "Konami" },
      { titulo: "Gauntlet IV", duracion: { principal: "7 h", extras: "8 h", completo: "10.5 h" }, anio: 1993, genero: "Acción / ARPG", desarrolladora: "M2 / SEGA" }
    ]
  },
  {
    consola: "Sega CD / Mega-CD",
    lista: [
      { titulo: "Flashback: The Quest for Identity", duracion: { principal: "5 h", extras: "6 h", completo: "7 h" }, anio: 1993, genero: "Plataformas Cinematográfico / Ciencia Ficción", desarrolladora: "Delphine Software" },
      { titulo: "Snatcher", duracion: { principal: "8 h", extras: "9.5 h", completo: "9.5 h" }, anio: 1994, genero: "Novela Visual / Aventura Gráfica", desarrolladora: "Konami" },
      { titulo: "Sonic CD", duracion: { principal: "2 h", extras: "3.5 h", completo: "6 h" }, anio: 1993, genero: "Plataformas", desarrolladora: "Sonic Team / SEGA" },
      { titulo: "Popful Mail", duracion: { principal: "13.5 h", extras: "16 h", completo: "19 h" }, anio: 1994, genero: "ARPG / Plataformas", desarrolladora: "Nihon Falcom / Working Designs" },
      { titulo: "Final Fight CD", duracion: { principal: "1 h", extras: "1.5 h", completo: "2 h" }, anio: 1993, genero: "Beat 'em up", desarrolladora: "Capcom / SEGA" },
      { titulo: "Jurassic Park", duracion: { principal: "3 h", extras: "4 h", completo: "5 h" }, anio: 1993, genero: "Aventura Point-and-Click", desarrolladora: "SEGA" },
      { titulo: "Lunar: The Silver Star", duracion: { principal: "22 h", extras: "25 h", completo: "29 h" }, anio: 1992, genero: "JRPG", desarrolladora: "Game Arts" },
      { titulo: "Dracula Unleashed", duracion: { principal: "5 h", extras: "6.5 h", completo: "8 h" }, anio: 1993, genero: "FMV / Película Interactiva", desarrolladora: "Viacom New Media" }
    ]
  },
  {
    consola: "Game Boy",
    lista: [
      { titulo: "Avenging Spirit", duracion: { principal: "45 min", extras: "1 h", completo: "1 h" }, anio: 1992, genero: "Acción / Plataformas", desarrolladora: "Jaleco" },
      { titulo: "Mole Mania", duracion: { principal: "5 h", extras: "7 h", completo: "9 h" }, anio: 1996, genero: "Puzle / Acción", desarrolladora: "Nintendo EAD / Pax Softnica" },
      { titulo: "Monster Max", duracion: { principal: "8 h", extras: "10 h", completo: "12 h" }, anio: 1994, genero: "Aventura / Puzle", desarrolladora: "Rare" },
      { titulo: "Kirby's Dream Land 2", duracion: { principal: "2.5 h", extras: "3.5 h", completo: "4.5 h" }, anio: 1995, genero: "Plataformas", desarrolladora: "HAL Laboratory" },
      { titulo: "Tiny Toon Adventures: Babs' Big Break", duracion: { principal: "1 h", extras: "1.5 h", completo: "2 h" }, anio: 1992, genero: "Plataformas", desarrolladora: "Konami" },
      { titulo: "Gargoyle's Quest", duracion: { principal: "3 h", extras: "3.5 h", completo: "4 h" }, anio: 1990, genero: "Acción / Plataformas", desarrolladora: "Capcom" },
      { titulo: "Amazing Tater", duracion: { principal: "7 h", extras: "7 h", completo: "7.5 h" }, anio: 1991, genero: "Puzle", desarrolladora: "Atlus" },
      { titulo: "Super Mario Land 2: 6 Golden Coins", duracion: { principal: "2 h", extras: "2.5 h", completo: "3.5 h" }, anio: 1992, genero: "Plataformas", desarrolladora: "Nintendo R&D1" }
    ]
  },
  {
    consola: "Sega Saturn",
    lista: [
      { titulo: "Earthworm Jim 2", duracion: { principal: "3 h", extras: "4.5 h", completo: "6 h" }, anio: 1995, genero: "Plataformas / Acción", desarrolladora: "Shiny Entertainment" },
      { titulo: "NiGHTS into Dreams", duracion: { principal: "2.5 h", extras: "4 h", completo: "6.5 h" }, anio: 1996, genero: "Plataformas / Acción 3D", desarrolladora: "Sonic Team" },
      { titulo: "Guardian Heroes", duracion: { principal: "1.5 h", extras: "5.5 h", completo: "15 h" }, anio: 1996, genero: "Beat 'em up / RPG", desarrolladora: "Treasure" },
      { titulo: "Radiant Silvergun", duracion: { principal: "3 h", extras: "5 h", completo: "25.5 h" }, anio: 1998, genero: "Shoot 'em up", desarrolladora: "Treasure" },
      { titulo: "Burning Rangers", duracion: { principal: "2 h", extras: "3 h", completo: "4.5 h" }, anio: 1998, genero: "Acción 3D", desarrolladora: "Sonic Team" },
      { titulo: "Panzer Dragoon", duracion: { principal: "1.5 h", extras: "2 h", completo: "3 h" }, anio: 1995, genero: "Rail Shooter", desarrolladora: "Team Andromeda" },
      { titulo: "Panzer Dragoon II Zwei", duracion: { principal: "1.5 h", extras: "2 h", completo: "3.5 h" }, anio: 1996, genero: "Rail Shooter", desarrolladora: "Team Andromeda" },
      { titulo: "Fighters Megamix", duracion: { principal: "1 h", extras: "2 h", completo: "8 h" }, anio: 1996, genero: "Lucha", desarrolladora: "Sega AM2" },
      { titulo: "Die Hard Arcade", duracion: { principal: "40 min", extras: "1 h", completo: "1.5 h" }, anio: 1996, genero: "Beat 'em up", desarrolladora: "Sega AM1" },
      { titulo: "Astal", duracion: { principal: "1.5 h", extras: "2 h", completo: "2.5 h" }, anio: 1995, genero: "Plataformas", desarrolladora: "SEGA" },
      { titulo: "Clockwork Knight", duracion: { principal: "1.5 h", extras: "2 h", completo: "3 h" }, anio: 1994, genero: "Plataformas", desarrolladora: "SEGA" },
      { titulo: "Clockwork Knight 2", duracion: { principal: "1.5 h", extras: "2 h", completo: "3 h" }, anio: 1995, genero: "Plataformas", desarrolladora: "SEGA" },
      { titulo: "Deep Fear", duracion: { principal: "7 h", extras: "8 h", completo: "10 h" }, anio: 1998, genero: "Survival Horror", desarrolladora: "SEGA" },
      { titulo: "Enemy Zero", duracion: { principal: "10 h", extras: "11 h", completo: "13 h" }, anio: 1996, genero: "Survival Horror / Aventura", desarrolladora: "WARP" }
    ]
  },
  {
    consola: "PlayStation",
    lista: [
      { titulo: "Suikoden", duracion: { principal: "20.5 h", extras: "24 h", completo: "26.5 h" }, anio: 1995, genero: "JRPG", desarrolladora: "Konami" },
      { titulo: "Silent Hill", duracion: { principal: "7 h", extras: "9.5 h", completo: "14.5 h" }, anio: 1999, genero: "Survival Horror", desarrolladora: "Team Silent / Konami" },
      { titulo: "Crash Bandicoot 2: Cortex Strikes Back", duracion: { principal: "5.5 h", extras: "7.5 h", completo: "12 h" }, anio: 1997, genero: "Plataformas", desarrolladora: "Naughty Dog" },
      { titulo: "Driver 2", duracion: { principal: "9 h", extras: "11 h", completo: "13 h" }, anio: 2000, genero: "Acción / Conducción", desarrolladora: "Reflections Interactive" },
      { titulo: "Crash Team Racing", duracion: { principal: "6.5 h", extras: "11 h", completo: "20 h" }, anio: 1999, genero: "Carreras / Karting", desarrolladora: "Naughty Dog" },
      { titulo: "Dino Crisis", duracion: { principal: "6.5 h", extras: "8 h", completo: "10 h" }, anio: 1999, genero: "Survival Horror", desarrolladora: "Capcom" },
      { titulo: "Syphon Filter", duracion: { principal: "8 h", extras: "11 h", completo: "15.5 h" }, anio: 1999, genero: "Acción / Sigilo", desarrolladora: "Eidetic" },
      { titulo: "Fear Effect", duracion: { principal: "9 h", extras: "11 h", completo: "13 h" }, anio: 2000, genero: "Acción / Survival Horror", desarrolladora: "Kronos Digital Entertainment" },
      { titulo: "Heart of Darkness", duracion: { principal: "5.5 h", extras: "7 h", completo: "9 h" }, anio: 1998, genero: "Plataformas / Aventura", desarrolladora: "Amazing Studio" },
      { titulo: "Vagrant Story", duracion: { principal: "22 h", extras: "29 h", completo: "41 h" }, anio: 2000, genero: "JRPG / Acción", desarrolladora: "Square" },
      { titulo: "Spyro: Year of the Dragon", duracion: { principal: "9.5 h", extras: "13 h", completo: "18 h" }, anio: 2000, genero: "Plataformas 3D", desarrolladora: "Insomniac Games" },
      { titulo: "Koudelka", duracion: { principal: "13 h", extras: "16 h", completo: "22 h" }, anio: 1999, genero: "JRPG / Survival Horror", desarrolladora: "Sacnoth" },
      { titulo: "Galerians", duracion: { principal: "7.5 h", extras: "9 h", completo: "11 h" }, anio: 1999, genero: "Survival Horror", desarrolladora: "Polygon Magic" },
      { titulo: "The Jungle Book: Mowgli's Wild Adventure", duracion: { principal: "2 h", extras: "3 h", completo: "4 h" }, anio: 2000, genero: "Plataformas", desarrolladora: "Ubi Soft" }
    ]
  },
  {
    consola: "Nintendo 64",
    lista: [
      { titulo: "Paper Mario", duracion: { principal: "22 h", extras: "26 h", completo: "32 h" }, anio: 2000, genero: "RPG", desarrolladora: "Intelligent Systems" },
      { titulo: "GoldenEye 007", duracion: { principal: "9.5 h", extras: "12 h", completo: "23 h" }, anio: 1997, genero: "FPS / Acción", desarrolladora: "Rare" },
      { titulo: "Banjo-Kazooie", duracion: { principal: "11 h", extras: "13 h", completo: "15.5 h" }, anio: 1998, genero: "Plataformas 3D", desarrolladora: "Rare" },
      { titulo: "Conker's Bad Fur Day", duracion: { principal: "11 h", extras: "13 h", completo: "17 h" }, anio: 2001, genero: "Plataformas 3D / Acción", desarrolladora: "Rare" },
      { titulo: "Ogre Battle 64", duracion: { principal: "34 h", extras: "50 h", completo: "70 h" }, anio: 1999, genero: "RPG Táctico", desarrolladora: "Quest" },
      { titulo: "Donkey Kong 64", duracion: { principal: "23 h", extras: "30.5 h", completo: "49 h" }, anio: 1999, genero: "Plataformas 3D", desarrolladora: "Rare" },
      { titulo: "Turok 2: Seeds of Evil", duracion: { principal: "15.5 h", extras: "18 h", completo: "21 h" }, anio: 1998, genero: "FPS / Acción", desarrolladora: "Iguana Entertainment" },
      { titulo: "Star Wars: Rogue Squadron", duracion: { principal: "8.5 h", extras: "11 h", completo: "15 h" }, anio: 1998, genero: "Acción / Combate Vehicular", desarrolladora: "Factor 5" },
      { titulo: "Blast Corps", duracion: { principal: "5.5 h", extras: "10 h", completo: "16 h" }, anio: 1997, genero: "Acción / Puzle", desarrolladora: "Rare" },
      { titulo: "Sin and Punishment", duracion: { principal: "2 h", extras: "2.5 h", completo: "3 h" }, anio: 2000, genero: "Rail Shooter", desarrolladora: "Treasure" },
      { titulo: "Excitebike 64", duracion: { principal: "6 h", extras: "11 h", completo: "20 h" }, anio: 2000, genero: "Carreras / Deportes", desarrolladora: "Left Field Productions" },
      { titulo: "Shadow Man", duracion: { principal: "18 h", extras: "22 h", completo: "27 h" }, anio: 1999, genero: "Acción / Aventura", desarrolladora: "Acclaim Studios Teesside" },
      { titulo: "Mario Tennis", duracion: { principal: "2.5 h", extras: "6 h", completo: "12 h" }, anio: 2000, genero: "Deportes", desarrolladora: "Camelot Software Planning" }
    ]
  },
  {
    consola: "Game Boy Color",
    lista: [
      { titulo: "Magi Nation", duracion: { principal: "24.5 h", extras: "30 h", completo: "38 h" }, anio: 2001, genero: "JRPG", desarrolladora: "Interactive Imagination" },
      { titulo: "Dragonyhm", duracion: { principal: "5.5 h", extras: "7 h", completo: "9 h" }, anio: 2020, genero: "RPG / Aventura", desarrolladora: "Spacebot Interactive" },
      { titulo: "The Legend of Zelda: Link's Awakening DX", duracion: { principal: "14 h", extras: "16.5 h", completo: "21 h" }, anio: 1998, genero: "Acción / Aventura", desarrolladora: "Nintendo EAD" },
      { titulo: "Metal Gear Ghost Babel", duracion: { principal: "8.5 h", extras: "10.5 h", completo: "13 h" }, anio: 2000, genero: "Acción / Sigilo", desarrolladora: "KCEJ / Konami" },
      { titulo: "Mario Tennis (GB)", duracion: { principal: "11.5 h", extras: "18 h", completo: "28 h" }, anio: 2000, genero: "Deportes / RPG", desarrolladora: "Camelot Software Planning" },
      { titulo: "Wario Land 3", duracion: { principal: "10.5 h", extras: "12.5 h", completo: "16 h" }, anio: 2000, genero: "Plataformas", desarrolladora: "Nintendo R&D1" },
      { titulo: "Warlocked", duracion: { principal: "5.5 h", extras: "7 h", completo: "9.5 h" }, anio: 2000, genero: "Estrategia (RTS)", desarrolladora: "Bits Studios" },
      { titulo: "Survival Kids", duracion: { principal: "8 h", extras: "11 h", completo: "15 h" }, anio: 1999, genero: "RPG / Supervivencia", desarrolladora: "Konami" },
      { titulo: "Looney Tunes: Marvin Strikes Back!", duracion: { principal: "4 h", extras: "5 h", completo: "6.5 h" }, anio: 2000, genero: "Acción / Aventura", desarrolladora: "Warthog Games" },
      { titulo: "Shantae", duracion: { principal: "8.5 h", extras: "10 h", completo: "12 h" }, anio: 2002, genero: "Plataformas / Metroidvania", desarrolladora: "WayForward" },
      { titulo: "Tomb Raider Starring Lara Croft", duracion: { principal: "6 h", extras: "7 h", completo: "8.5 h" }, anio: 2000, genero: "Acción / Plataformas", desarrolladora: "Core Design" },
      { titulo: "Spy vs. Spy", duracion: { principal: "2.5 h", extras: "3 h", completo: "4 h" }, anio: 1999, genero: "Estrategia / Acción", desarrolladora: "Kemco" }
    ]
  },
  {
    consola: "PlayStation 2",
    lista: [
      { titulo: "Kingdom Hearts", duracion: { principal: "28.5 h", extras: "42 h", completo: "62.5 h" }, anio: 2002, genero: "JRPG / Acción", desarrolladora: "Square" },
      { titulo: "Final Fantasy X", duracion: { principal: "45.5 h", extras: "67 h", completo: "144 h" }, anio: 2001, genero: "JRPG", desarrolladora: "Square" },
      { titulo: "Spyro: Enter the Dragonfly", duracion: { principal: "9.5 h", extras: "10.5 h", completo: "11.5 h" }, anio: 2002, genero: "Plataformas 3D", desarrolladora: "Check Five Games" },
      { titulo: "Sly Cooper and the Thievius Raccoonus", duracion: { principal: "8.5 h", extras: "10 h", completo: "12.5 h" }, anio: 2002, genero: "Plataformas / Sigilo", desarrolladora: "Sucker Punch Productions" },
      { titulo: "Evil Dead: Regeneration", duracion: { principal: "6 h", extras: "6 h", completo: "6.5 h" }, anio: 2005, genero: "Acción / Hack and Slash", desarrolladora: "Cranky Pants Games" },
      { titulo: "God of War", duracion: { principal: "9 h", extras: "10 h", completo: "12 h" }, anio: 2005, genero: "Hack and Slash / Acción", desarrolladora: "Santa Monica Studio" },
      { titulo: "Metal Gear Solid 2: Substance", duracion: { principal: "13.5 h", extras: "22 h", completo: "47.5 h" }, anio: 2002, genero: "Acción / Sigilo", desarrolladora: "Konami" },
      { titulo: "Ico", duracion: { principal: "6.5 h", extras: "7 h", completo: "8 h" }, anio: 2001, genero: "Aventura / Puzle", desarrolladora: "Team Ico" },
      { titulo: "Ratchet & Clank", duracion: { principal: "12 h", extras: "15 h", completo: "25 h" }, anio: 2002, genero: "Plataformas / Acción", desarrolladora: "Insomniac Games" },
      { titulo: "Katamari Damacy", duracion: { principal: "6 h", extras: "8 h", completo: "14 h" }, anio: 2004, genero: "Puzle / Acción", desarrolladora: "Namco" },
      { titulo: "The Warriors", duracion: { principal: "11 h", extras: "13 h", completo: "16.5 h" }, anio: 2005, genero: "Beat 'em up / Acción", desarrolladora: "Rockstar Toronto" },
      { titulo: "Def Jam: Fight for NY", duracion: { principal: "6 h", extras: "8 h", completo: "13 h" }, anio: 2004, genero: "Lucha", desarrolladora: "AKI Corporation" },
      { titulo: "WWE SmackDown! Here Comes the Pain", duracion: { principal: "14.5 h", extras: "40 h", completo: "124 h" }, anio: 2003, genero: "Lucha Libre / Deportes", desarrolladora: "Yuke's" },
      { titulo: "Jak and Daxter: The Precursor Legacy", duracion: { principal: "10 h", extras: "11.5 h", completo: "12 h" }, anio: 2001, genero: "Plataformas 3D", desarrolladora: "Naughty Dog" },
      { titulo: "Rule of Rose", duracion: { principal: "8.5 h", extras: "10 h", completo: "10 h" }, anio: 2006, genero: "Survival Horror", desarrolladora: "Punchline" },
      { titulo: "Haunting Ground", duracion: { principal: "9 h", extras: "9.5 h", completo: "11.5 h" }, anio: 2005, genero: "Survival Horror", desarrolladora: "Capcom" },
      { titulo: "SMT: Digital Devil Saga", duracion: { principal: "30.5 h", extras: "41.5 h", completo: "73.5 h" }, anio: 2004, genero: "JRPG", desarrolladora: "Atlus" },
      { titulo: "Mortal Kombat: Shaolin Monks", duracion: { principal: "7 h", extras: "9 h", completo: "14 h" }, anio: 2005, genero: "Beat 'em up / Acción", desarrolladora: "Midway" },
      { titulo: "Downhill Domination", duracion: { principal: "4.5 h", extras: "10 h", completo: "50 h" }, anio: 2003, genero: "Carreras / Deportes", desarrolladora: "Incognito Entertainment" },
      { titulo: "Burnout 3: Takedown", duracion: { principal: "13 h", extras: "16 h", completo: "27 h" }, anio: 2004, genero: "Carreras / Arcade", desarrolladora: "Criterion Games" },
      { titulo: "Rogue Galaxy", duracion: { principal: "38.5 h", extras: "61 h", completo: "106 h" }, anio: 2005, genero: "JRPG / Acción", desarrolladora: "Level-5" },
      { titulo: "Dark Chronicle / Dark Cloud 2", duracion: { principal: "50.5 h", extras: "69 h", completo: "135 h" }, anio: 2002, genero: "JRPG / Acción", desarrolladora: "Level-5" },
      { titulo: "Dirge of Cerberus: FFVII", duracion: { principal: "11.5 h", extras: "15 h", completo: "34 h" }, anio: 2006, genero: "Shooter / Acción", desarrolladora: "Square Enix" },
      { titulo: "Onimusha 3: Demon Siege", duracion: { principal: "12 h", extras: "15.5 h", completo: "20 h" }, anio: 2004, genero: "Hack and Slash / Acción", desarrolladora: "Capcom" },
      { titulo: "Shadow of Rome", duracion: { principal: "15 h", extras: "19 h", completo: "25 h" }, anio: 2005, genero: "Hack and Slash / Acción", desarrolladora: "Capcom" },
      { titulo: "Urban Chaos: Riot Response", duracion: { principal: "8 h", extras: "12 h", completo: "14 h" }, anio: 2006, genero: "FPS / Acción", desarrolladora: "Rocksteady Studios" },
      { titulo: "Disaster Report", duracion: { principal: "5.5 h", extras: "7 h", completo: "11 h" }, anio: 2002, genero: "Aventura / Supervivencia", desarrolladora: "Irem" },
      { titulo: "Rise to Honor", duracion: { principal: "6 h", extras: "7 h", completo: "9 h" }, anio: 2004, genero: "Beat 'em up / Acción", desarrolladora: "Foster City Studio" },
      { titulo: "Forbidden Siren 2", duracion: { principal: "18.5 h", extras: "24 h", completo: "35 h" }, anio: 2006, genero: "Survival Horror", desarrolladora: "Project Siren" },
      { titulo: "Gregory Horror Show", duracion: { principal: "6 h", extras: "8 h", completo: "12 h" }, anio: 2003, genero: "Aventura / Survival Horror", desarrolladora: "Capcom" },
      { titulo: "Clock Tower 3", duracion: { principal: "6.5 h", extras: "8 h", completo: "10 h" }, anio: 2002, genero: "Survival Horror", desarrolladora: "Capcom / Sunsoft" },
      { titulo: "Spider-Man 2", duracion: { principal: "7.5 h", extras: "10.5 h", completo: "19 h" }, anio: 2004, genero: "Acción / Mundo Abierto", desarrolladora: "Treyarch" },
      { titulo: "Dragon Ball Z: Budokai 3", duracion: { principal: "10 h", extras: "14 h", completo: "22 h" }, anio: 2004, genero: "Lucha", desarrolladora: "Dimps" },
      { titulo: "Shinobi", duracion: { principal: "8 h", extras: "11 h", completo: "18 h" }, anio: 2002, genero: "Hack and Slash / Acción", desarrolladora: "Overworks" },
      { titulo: "Urban Reign", duracion: { principal: "6.5 h", extras: "8 h", completo: "11 h" }, anio: 2005, genero: "Beat 'em up", desarrolladora: "Namco" },
      { titulo: "Call of Duty 3", duracion: { principal: "8 h", extras: "9 h", completo: "10.5 h" }, anio: 2006, genero: "FPS", desarrolladora: "Treyarch" },
      { titulo: "Metal Gear Solid 3: Subsistence", duracion: { principal: "16 h", extras: "21 h", completo: "32 h" }, anio: 2005, genero: "Acción / Sigilo", desarrolladora: "Konami" },
      { titulo: "Guilty Gear X Plus", duracion: { principal: "2 h", extras: "4 h", completo: "12 h" }, anio: 2001, genero: "Lucha", desarrolladora: "Arc System Works" },
      { titulo: "God Hand", duracion: { principal: "13 h", extras: "18 h", completo: "29 h" }, anio: 2006, genero: "Beat 'em up", desarrolladora: "Clover Studio" },
      { titulo: "Peter Jackson's King Kong", duracion: { principal: "6 h", extras: "7 h", completo: "8.5 h" }, anio: 2005, genero: "Acción / FPS", desarrolladora: "Ubisoft Montpellier" },
      { titulo: "Psychonauts", duracion: { principal: "12 h", extras: "14 h", completo: "18 h" }, anio: 2005, genero: "Plataformas 3D", desarrolladora: "Double Fine Productions" }
    ]
  },
  {
    consola: "Sega Dreamcast",
    lista: [
      { titulo: "Shenmue", duracion: { principal: "18 h", extras: "24 h", completo: "32 h" }, anio: 1999, genero: "Aventura / Mundo Abierto", desarrolladora: "SEGA AM2" },
      { titulo: "Resident Evil 2", duracion: { principal: "6 h", extras: "8 h", completo: "11 h" }, anio: 1999, genero: "Survival Horror", desarrolladora: "Capcom" },
      { titulo: "Dead or Alive 2", duracion: { principal: "1 h", extras: "2.5 h", completo: "9 h" }, anio: 2000, genero: "Lucha", desarrolladora: "Team Ninja" },
      { titulo: "Marvel vs. Capcom 2", duracion: { principal: "1 h", extras: "3 h", completo: "20 h" }, anio: 2000, genero: "Lucha", desarrolladora: "Capcom" },
      { titulo: "Rez", duracion: { principal: "1.5 h", extras: "2.5 h", completo: "7 h" }, anio: 2001, genero: "Rail Shooter / Rítmico", desarrolladora: "United Game Artists" },
      { titulo: "Headhunter", duracion: { principal: "11.5 h", extras: "14 h", completo: "17 h" }, anio: 2001, genero: "Acción / Sigilo", desarrolladora: "Amuze" },
      { titulo: "Sturmwind", duracion: { principal: "2 h", extras: "3.5 h", completo: "6 h" }, anio: 2013, genero: "Shoot 'em up", desarrolladora: "Duranik" },
      { titulo: "Giga Wing", duracion: { principal: "45 min", extras: "1.5 h", completo: "5 h" }, anio: 1999, genero: "Shoot 'em up", desarrolladora: "Takumi" },
      { titulo: "The House of the Dead 2", duracion: { principal: "45 min", extras: "1 h", completo: "3 h" }, anio: 1999, genero: "Rail Shooter", desarrolladora: "Sega AM1" },
      { titulo: "Spider-Man", duracion: { principal: "4.5 h", extras: "6 h", completo: "8 h" }, anio: 2000, genero: "Acción / Aventura", desarrolladora: "Neversoft" }
    ]
  },
{
    consola: "Nintendo GameCube",
    lista: [
      { titulo: "The Legend of Zelda: The Wind Waker", duracion: { principal: "29 h", extras: "42 h", completo: "60 h" }, anio: 2002, genero: "Acción / Aventura", desarrolladora: "Nintendo EAD" },
      { titulo: "Super Mario Sunshine", duracion: { principal: "15 h", extras: "21 h", completo: "29.5 h" }, anio: 2002, genero: "Plataformas 3D", desarrolladora: "Nintendo EAD" },
      { titulo: "Resident Evil 4", duracion: { principal: "15.5 h", extras: "22 h", completo: "31.5 h" }, anio: 2005, genero: "Survival Horror / Acción", desarrolladora: "Capcom" },
      { titulo: "Paper Mario: The Thousand-Year Door", duracion: { principal: "30.5 h", extras: "44 h", completo: "63 h" }, anio: 2004, genero: "RPG", desarrolladora: "Intelligent Systems" },
      { titulo: "Fire Emblem: Path of Radiance", duracion: { principal: "33 h", extras: "39 h", completo: "44 h" }, anio: 2005, genero: "RPG Táctico", desarrolladora: "Intelligent Systems" },
      { titulo: "Metroid Prime", duracion: { principal: "14 h", extras: "19 h", completo: "27 h" }, anio: 2002, genero: "FPS / Aventura", desarrolladora: "Retro Studios" },
      { titulo: "Pikmin 2", duracion: { principal: "11.5 h", extras: "16 h", completo: "23 h" }, anio: 2004, genero: "Estrategia / Puzle", desarrolladora: "Nintendo EAD" },
      { titulo: "Viewtiful Joe", duracion: { principal: "8 h", extras: "10 h", completo: "13 h" }, anio: 2003, genero: "Beat 'em up / Acción", desarrolladora: "Clover Studio" },
      { titulo: "SoulCalibur II", duracion: { principal: "3.5 h", extras: "12 h", completo: "36.5 h" }, anio: 2003, genero: "Lucha", desarrolladora: "Project Soul / Namco" },
      { titulo: "Super Smash Bros. Melee", duracion: { principal: "4.5 h", extras: "11 h", completo: "41 h" }, anio: 2001, genero: "Lucha / Plataformas", desarrolladora: "HAL Laboratory" },
      { titulo: "Eternal Darkness: Sanity's Requiem", duracion: { principal: "13.5 h", extras: "18 h", completo: "24 h" }, anio: 2002, genero: "Survival Horror", desarrolladora: "Silicon Knights" },
      { titulo: "TimeSplitters 2", duracion: { principal: "8 h", extras: "10 h", completo: "13 h" }, anio: 2002, genero: "FPS", desarrolladora: "Free Radical Design" },
      { titulo: "Star Wars Rogue Squadron II: Rogue Leader", duracion: { principal: "6.5 h", extras: "8 h", completo: "11 h" }, anio: 2001, genero: "Acción / Combate Vehicular", desarrolladora: "Factor 5" },
      { titulo: "The Incredible Hulk: Ultimate Destruction", duracion: { principal: "8.5 h", extras: "11 h", completo: "16 h" }, anio: 2005, genero: "Acción / Mundo Abierto", desarrolladora: "Radical Entertainment" },
      { titulo: "X-Men Legends", duracion: { principal: "17.5 h", extras: "22 h", completo: "30 h" }, anio: 2004, genero: "ARPG / Acción", desarrolladora: "Raven Software" },
      { titulo: "Tom and Jerry in War of the Whiskers", duracion: { principal: "2 h", extras: "3 h", completo: "5 h" }, anio: 2002, genero: "Lucha / Party", desarrolladora: "VIS Entertainment" },
      { titulo: "Skies of Arcadia Legends", duracion: { principal: "46 h", extras: "58 h", completo: "84 h" }, anio: 2002, genero: "JRPG", desarrolladora: "Overworks" },
      { titulo: "Pikmin", duracion: { principal: "7.5 h", extras: "10 h", completo: "14 h" }, anio: 2001, genero: "Estrategia / Puzle", desarrolladora: "Nintendo EAD" },
      { titulo: "Prince of Persia: Warrior Within", duracion: { principal: "12 h", extras: "14.5 h", completo: "18 h" }, anio: 2004, genero: "Acción / Plataformas", desarrolladora: "Ubisoft Montreal" },
      { titulo: "Prince of Persia: The Two Thrones", duracion: { principal: "9.5 h", extras: "11 h", completo: "13 h" }, anio: 2005, genero: "Acción / Plataformas", desarrolladora: "Ubisoft Montreal" }
    ]
  },
  {
    consola: "Game Boy Advance",
    lista: [
      { titulo: "The Legend of Zelda: The Minish Cap", duracion: { principal: "11.5 h", extras: "15 h", completo: "20 h" }, anio: 2004, genero: "Acción / Aventura", desarrolladora: "Capcom / Flagship" },
      { titulo: "Metroid Fusion", duracion: { principal: "5 h", extras: "6.5 h", completo: "8.5 h" }, anio: 2002, genero: "Metroidvania / Acción", desarrolladora: "Nintendo R&D1" },
      { titulo: "Final Fantasy Tactics Advance", duracion: { principal: "43 h", extras: "66 h", completo: "105 h" }, anio: 2003, genero: "RPG Táctico", desarrolladora: "Square Enix" },
      { titulo: "Golden Sun: The Lost Age", duracion: { principal: "33.5 h", extras: "39 h", completo: "49 h" }, anio: 2002, genero: "JRPG", desarrolladora: "Camelot Software Planning" },
      { titulo: "Mario & Luigi: Superstar Saga", duracion: { principal: "18.5 h", extras: "22 h", completo: "26.5 h" }, anio: 2003, genero: "JRPG / Acción", desarrolladora: "AlphaDream" },
      { titulo: "Wario Land 4", duracion: { principal: "5.5 h", extras: "7 h", completo: "9 h" }, anio: 2001, genero: "Plataformas", desarrolladora: "Nintendo R&D1" },
      { titulo: "Mother 3", duracion: { principal: "27 h", extras: "31 h", completo: "36 h" }, anio: 2006, genero: "JRPG", desarrolladora: "HAL Laboratory / Brownie Brown" },
      { titulo: "Tactics Ogre: The Knight of Lodis", duracion: { principal: "30 h", extras: "42 h", completo: "62 h" }, anio: 2001, genero: "RPG Táctico", desarrolladora: "Quest" },
      { titulo: "Fire Emblem: The Sacred Stones", duracion: { principal: "22 h", extras: "27 h", completo: "37 h" }, anio: 2004, genero: "RPG Táctico", desarrolladora: "Intelligent Systems" },
      { titulo: "Super Robot Taisen: Original Generation 2", duracion: { principal: "29.5 h", extras: "38 h", completo: "55 h" }, anio: 2005, genero: "RPG Táctico", desarrolladora: "Banpresto" },
      { titulo: "Rhythm Tengoku", duracion: { principal: "4 h", extras: "8 h", completo: "15 h" }, anio: 2006, genero: "Rítmico", desarrolladora: "Nintendo SPD" },
      { titulo: "Klonoa: Empire of Dreams", duracion: { principal: "5 h", extras: "6.5 h", completo: "8 h" }, anio: 2001, genero: "Plataformas / Puzle", desarrolladora: "Namco" },
      { titulo: "Sonic Advance 2", duracion: { principal: "3 h", extras: "4 h", completo: "5.5 h" }, anio: 2002, genero: "Plataformas", desarrolladora: "Dimps / Sonic Team" },
      { titulo: "Shining Force: Resurrection of the Dark Dragon", duracion: { principal: "18.5 h", extras: "24 h", completo: "33 h" }, anio: 2004, genero: "RPG Táctico", desarrolladora: "Amusement Vision" },
      { titulo: "Castlevania: Circle of the Moon", duracion: { principal: "8.5 h", extras: "11 h", completo: "16 h" }, anio: 2001, genero: "Metroidvania / Acción", desarrolladora: "Konami" },
      { titulo: "Super Mario Advance 4: Super Mario Bros. 3", duracion: { principal: "5 h", extras: "6.5 h", completo: "8 h" }, anio: 2003, genero: "Plataformas", desarrolladora: "Nintendo EAD" }
    ]
  },
  {
    consola: "Nintendo Wii",
    lista: [
      { titulo: "New Super Mario Bros. Wii", duracion: { principal: "7 h", extras: "10 h", completo: "16.5 h" }, anio: 2009, genero: "Plataformas", desarrolladora: "Nintendo EAD" },
      { titulo: "Super Smash Bros. Brawl", duracion: { principal: "11.5 h", extras: "21 h", completo: "66 h" }, anio: 2008, genero: "Lucha / Plataformas", desarrolladora: "Sora Ltd. / Game Arts" },
      { titulo: "Kirby's Return to Dream Land", duracion: { principal: "6.5 h", extras: "9 h", completo: "13 h" }, anio: 2011, genero: "Plataformas", desarrolladora: "HAL Laboratory" },
      { titulo: "Donkey Kong Country Returns", duracion: { principal: "11 h", extras: "15 h", completo: "23 h" }, anio: 2010, genero: "Plataformas", desarrolladora: "Retro Studios" },
      { titulo: "Super Mario Galaxy", duracion: { principal: "13 h", extras: "18 h", completo: "33.5 h" }, anio: 2007, genero: "Plataformas 3D", desarrolladora: "Nintendo EAD Tokyo" },
      { titulo: "Xenoblade Chronicles", duracion: { principal: "67.5 h", extras: "88 h", completo: "148 h" }, anio: 2010, genero: "JRPG / Acción", desarrolladora: "Monolith Soft" },
      { titulo: "No More Heroes", duracion: { principal: "11 h", extras: "15 h", completo: "21 h" }, anio: 2007, genero: "Acción / Hack and Slash", desarrolladora: "Grasshopper Manufacture" },
      { titulo: "Super Paper Mario", duracion: { principal: "18.5 h", extras: "22 h", completo: "30 h" }, anio: 2007, genero: "RPG / Plataformas", desarrolladora: "Intelligent Systems" },
      { titulo: "Super Mario Galaxy 2", duracion: { principal: "13.5 h", extras: "18 h", completo: "35 h" }, anio: 2010, genero: "Plataformas", desarrolladora: "Nintendo EAD Tokyo" },
      { titulo: "Muramasa: The Demon Blade", duracion: { principal: "10.5 h", extras: "15 h", completo: "29 h" }, anio: 2009, genero: "Hack and Slash / Action RPG", desarrolladora: "Vanillaware" },
      { titulo: "Transformers Prime: The Game", duracion: { principal: "4 h", extras: "5 h", completo: "6 h" }, anio: 2012, genero: "Acción / Beat 'em up", desarrolladora: "Now Production" },
      { titulo: "Mega Man 9", duracion: { principal: "3.5 h", extras: "5 h", completo: "9 h" }, anio: 2008, genero: "Plataformas / Acción", desarrolladora: "Inti Creates / Capcom" },
      { titulo: "Rhythm Heaven Fever", duracion: { principal: "6.5 h", extras: "9 h", completo: "18 h" }, anio: 2011, genero: "Rítmico", desarrolladora: "Nintendo SPD / TNX" },
      { titulo: "Endless Ocean: Blue World", duracion: { principal: "15 h", extras: "20 h", completo: "30 h" }, anio: 2009, genero: "Aventura / Simulación", desarrolladora: "Arika" }
    ]
  },
  {
    consola: "Nintendo DS",
    lista: [
      { titulo: "The Legend of Zelda: Phantom Hourglass", duracion: { principal: "13.5 h", extras: "18 h", completo: "25 h" }, anio: 2007, genero: "Acción / Aventura", desarrolladora: "Nintendo EAD" },
      { titulo: "New Super Mario Bros.", duracion: { principal: "7 h", extras: "9 h", completo: "13 h" }, anio: 2006, genero: "Plataformas", desarrolladora: "Nintendo EAD" },
      { titulo: "Castlevania: Portrait of Ruin", duracion: { principal: "10 h", extras: "13 h", completo: "20 h" }, anio: 2006, genero: "Metroidvania / Acción", desarrolladora: "Konami" },
      { titulo: "Dragon Quest V: Hand of the Heavenly Bride", duracion: { principal: "30.5 h", extras: "38 h", completo: "48 h" }, anio: 2008, genero: "JRPG", desarrolladora: "ArtePiazza / Square Enix" },
      { titulo: "GTA: Chinatown Wars", duracion: { principal: "11 h", extras: "13 h", completo: "20 h" }, anio: 2009, genero: "Acción / Mundo Abierto", desarrolladora: "Rockstar Leeds" },
      { titulo: "Elite Beat Agents", duracion: { principal: "7 h", extras: "9 h", completo: "14 h" }, anio: 2006, genero: "Rítmico", desarrolladora: "iNiS / Nintendo" },
      { titulo: "Mario & Luigi: Bowser's Inside Story", duracion: { principal: "22.5 h", extras: "27 h", completo: "33 h" }, anio: 2009, genero: "JRPG / Acción", desarrolladora: "AlphaDream" },
      { titulo: "Ace Attorney - Trials and Tribulations", duracion: { principal: "20 h", extras: "21 h", completo: "22 h" }, anio: 2007, genero: "Aventura Visual / Misterio", desarrolladora: "Capcom" },
      { titulo: "Professor Layton and the Curious Village", duracion: { principal: "12 h", extras: "14 h", completo: "17 h" }, anio: 2007, genero: "Puzle / Aventura", desarrolladora: "Level-5" },
      { titulo: "Jump Ultimate Stars", duracion: { principal: "9.5 h", extras: "20 h", completo: "62 h" }, anio: 2006, genero: "Lucha", desarrolladora: "Ganbarion" },
      { titulo: "SMT: Devil Survivor", duracion: { principal: "31.5 h", extras: "55 h", completo: "78 h" }, anio: 2009, genero: "RPG Táctico", desarrolladora: "Atlus" },
      { titulo: "Ninja Gaiden: Dragon Sword", duracion: { principal: "6 h", extras: "7 h", completo: "10 h" }, anio: 2008, genero: "Acción / Hack and Slash", desarrolladora: "Team Ninja" },
      { titulo: "Trauma Center: Under the Knife 2", duracion: { principal: "9.5 h", extras: "11 h", completo: "13 h" }, anio: 2008, genero: "Simulación / Puzle", desarrolladora: "Vanguard Works / Atlus" },
      { titulo: "Lock's Quest", duracion: { principal: "13.5 h", extras: "16 h", completo: "20 h" }, anio: 2008, genero: "Estrategia / Tower Defense", desarrolladora: "5th Cell" },
      { titulo: "Sonic Colors", duracion: { principal: "4.5 h", extras: "6 h", completo: "8.5 h" }, anio: 2010, genero: "Plataformas", desarrolladora: "Dimps / Sonic Team" },
      { titulo: "Age of Empires: The Age of Kings", duracion: { principal: "18 h", extras: "25 h", completo: "35 h" }, anio: 2006, genero: "Estrategia por Turnos", desarrolladora: "Backbone Entertainment" },
      { titulo: "Yoshi's Island DS", duracion: { principal: "9.5 h", extras: "12 h", completo: "16 h" }, anio: 2006, genero: "Plataformas", desarrolladora: "Artoon" },
      { titulo: "Diddy Kong Racing DS", duracion: { principal: "6.5 h", extras: "10 h", completo: "16 h" }, anio: 2007, genero: "Carreras", desarrolladora: "Rare" },
      { titulo: "Kirby: Squeak Squad", duracion: { principal: "5 h", extras: "7 h", completo: "10 h" }, anio: 2006, genero: "Plataformas", desarrolladora: "Flagship / HAL Laboratory" }
    ]
  },
  {
    consola: "PSP",
    lista: [
      { titulo: "Metal Gear Solid: Peace Walker", duracion: { principal: "15.5 h", extras: "24 h", completo: "96 h" }, anio: 2010, genero: "Acción / Sigilo", desarrolladora: "Kojima Productions" },
      { titulo: "Jeanne d'Arc", duracion: { principal: "33.5 h", extras: "40 h", completo: "50 h" }, anio: 2006, genero: "RPG Táctico", desarrolladora: "Level-5" },
      { titulo: "Secret Agent Clank", duracion: { principal: "7 h", extras: "9 h", completo: "15 h" }, anio: 2008, genero: "Plataformas / Acción", desarrolladora: "High Impact Games" },
      { titulo: "Killzone: Liberation", duracion: { principal: "6.5 h", extras: "9 h", completo: "29 h" }, anio: 2006, genero: "Shooter Táctico / Acción", desarrolladora: "Guerrilla Games" },
      { titulo: "Gurumin: A Monstrous Adventure", duracion: { principal: "11.5 h", extras: "20 h", completo: "45 h" }, anio: 2004, genero: "Action RPG / Plataformas", desarrolladora: "Nihon Falcom" },
      { titulo: "Persona 3 Portable", duracion: { principal: "65.5 h", extras: "80 h", completo: "123 h" }, anio: 2009, genero: "JRPG", desarrolladora: "Atlus" },
      { titulo: "Tactics Ogre: Let Us Cling Together", duracion: { principal: "56.5 h", extras: "71 h", completo: "137 h" }, anio: 2010, genero: "RPG Táctico", desarrolladora: "Square Enix" },
      { titulo: "Monster Hunter Freedom Unite", duracion: { principal: "78.5 h", extras: "262 h", completo: "580 h" }, anio: 2008, genero: "Action RPG", desarrolladora: "Capcom" },
      { titulo: "Kingdom Hearts: Birth by Sleep", duracion: { principal: "26.5 h", extras: "41 h", completo: "73.5 h" }, anio: 2010, genero: "Action RPG", desarrolladora: "Square Enix" },
      { titulo: "Final Fantasy Tactics: War of the Lions", duracion: { principal: "38.5 h", extras: "59 h", completo: "84.5 h" }, anio: 2007, genero: "RPG Táctico", desarrolladora: "Square Enix" },
      { titulo: "Disgaea 2: Dark Hero Days", duracion: { principal: "41.5 h", extras: "65 h", completo: "142 h" }, anio: 2009, genero: "RPG Táctico", desarrolladora: "Nippon Ichi Software" },
      { titulo: "Ghost Rider", duracion: { principal: "4.5 h", extras: "5.5 h", completo: "6.5 h" }, anio: 2007, genero: "Hack and Slash / Acción", desarrolladora: "Climax Group" },
      { titulo: "The Legend of Heroes: Trails in the Sky", duracion: { principal: "50.5 h", extras: "65 h", completo: "83 h" }, anio: 2004, genero: "JRPG", desarrolladora: "Nihon Falcom" },
      { titulo: "Phantasy Star Portable 2", duracion: { principal: "26.5 h", extras: "68 h", completo: "210 h" }, anio: 2009, genero: "Action RPG", desarrolladora: "Alfa System / Sega" },
      { titulo: "Patapon", duracion: { principal: "13.5 h", extras: "18 h", completo: "29 h" }, anio: 2007, genero: "Rítmico / Estrategia", desarrolladora: "Pyramid / Japan Studio" },
      { titulo: "LittleBigPlanet", duracion: { principal: "5.5 h", extras: "10 h", completo: "22 h" }, anio: 2009, genero: "Plataformas", desarrolladora: "SCE Cambridge Studio" },
      { titulo: "Kenka Bancho: Badass Rumble", duracion: { principal: "6.5 h", extras: "10 h", completo: "18 h" }, anio: 2008, genero: "Beat 'em up / Acción", desarrolladora: "Spike" },
      { titulo: "Dante's Inferno", duracion: { principal: "6 h", extras: "7 h", completo: "9 h" }, anio: 2010, genero: "Hack and Slash / Acción", desarrolladora: "A2M" },
      { titulo: "Resistance: Retribution", duracion: { principal: "8 h", extras: "9.5 h", completo: "13 h" }, anio: 2009, genero: "TPS / Acción", desarrolladora: "Bend Studio" },
      { titulo: "Tenchu: Shadow Assassins", duracion: { principal: "7.5 h", extras: "9 h", completo: "12 h" }, anio: 2009, genero: "Sigilo / Acción", desarrolladora: "Acquire" },
      { titulo: "Silent Hill: Origins", duracion: { principal: "6 h", extras: "7 h", completo: "9 h" }, anio: 2007, genero: "Survival Horror", desarrolladora: "Climax Action" },
      { titulo: "Corpse Party", duracion: { principal: "11 h", extras: "14 h", completo: "20 h" }, anio: 2010, genero: "Survival Horror / Aventura", desarrolladora: "Team GrisGris / 5pb." },
      { titulo: "Class of Heroes", duracion: { principal: "38.5 h", extras: "55 h", completo: "80 h" }, anio: 2008, genero: "Dungeon Crawler / RPG", desarrolladora: "ZeroDiv" },
      { titulo: "Crisis Core: Final Fantasy VII", duracion: { principal: "18 h", extras: "24 h", completo: "36 h" }, anio: 2007, genero: "Action RPG", desarrolladora: "Square Enix" },
      { titulo: "PixelJunk Monsters Deluxe", duracion: { principal: "15.5 h", extras: "25 h", completo: "50 h" }, anio: 2009, genero: "Tower Defense / Estrategia", desarrolladora: "Q-Games" },
      { titulo: "Syphon Filter: Dark Mirror", duracion: { principal: "7.5 h", extras: "9 h", completo: "12 h" }, anio: 2006, genero: "TPS / Sigilo", desarrolladora: "Bend Studio" },
      { titulo: "Tekken 5: Dark Resurrection", duracion: { principal: "1.5 h", extras: "4 h", completo: "16 h" }, anio: 2006, genero: "Lucha", desarrolladora: "Bandai Namco Games" },
      { titulo: "Monster Hunter Portable 3rd", duracion: { principal: "63.5 h", extras: "172 h", completo: "380 h" }, anio: 2010, genero: "Action RPG", desarrolladora: "Capcom" },
      { titulo: "Persona 1", duracion: { principal: "31.5 h", extras: "39 h", completo: "56 h" }, anio: 2009, genero: "JRPG", desarrolladora: "Atlus" }
    ]
  },
  {
    consola: "Nintendo 3DS",
    lista: [
      { titulo: "3D Shinobi III", duracion: { principal: "2 h", extras: "3 h", completo: "4 h" }, anio: 2013, genero: "Acción / Plataformas", desarrolladora: "M2 / SEGA" },
      { titulo: "Dragon Quest Monsters: Terry's Wonderland 3D", duracion: { principal: "27 h", extras: "45 h", completo: "88 h" }, anio: 2012, genero: "JRPG / Captura de Monstruos", desarrolladora: "Square Enix" },
      { titulo: "Dragon Quest VIII", duracion: { principal: "61.5 h", extras: "85 h", completo: "130 h" }, anio: 2015, genero: "JRPG", desarrolladora: "Level-5 / Square Enix" },
      { titulo: "The Legend of Zelda: A Link Between Worlds", duracion: { principal: "13.5 h", extras: "17 h", completo: "23 h" }, anio: 2013, genero: "Acción / Aventura", desarrolladora: "Nintendo EAD" },
      { titulo: "Super Mario 3D Land", duracion: { principal: "7 h", extras: "10 h", completo: "19 h" }, anio: 2011, genero: "Plataformas 3D", desarrolladora: "Nintendo EAD Tokyo" },
      { titulo: "Fire Emblem: Awakening", duracion: { principal: "28 h", extras: "36 h", completo: "62 h" }, anio: 2012, genero: "RPG Táctico", desarrolladora: "Intelligent Systems" },
      { titulo: "Shovel Knight", duracion: { principal: "7 h", extras: "9 h", completo: "16 h" }, anio: 2014, genero: "Plataformas / Acción", desarrolladora: "Yacht Club Games" },
      { titulo: "Super Smash Bros. for 3DS", duracion: { principal: "2.5 h", extras: "12 h", completo: "41 h" }, anio: 2014, genero: "Lucha / Plataformas", desarrolladora: "Bandai Namco Studios / Sora Ltd." },
      { titulo: "Pushmo", duracion: { principal: "10 h", extras: "14 h", completo: "20 h" }, anio: 2011, genero: "Puzle", desarrolladora: "Intelligent Systems" },
      { titulo: "Metroid: Samus Returns", duracion: { principal: "11 h", extras: "13 h", completo: "17 h" }, anio: 2017, genero: "Metroidvania / Acción", desarrolladora: "MercurySteam / Nintendo" },
      { titulo: "Mutant Mudds: Super Challenge", duracion: { principal: "4 h", extras: "6 h", completo: "8 h" }, anio: 2016, genero: "Plataformas", desarrolladora: "Renegade Kid" },
      { titulo: "Pokémon Sun", duracion: { principal: "32.5 h", extras: "50 h", completo: "106 h" }, anio: 2016, genero: "JRPG / Captura de Monstruos", desarrolladora: "Game Freak" },
      { titulo: "Mario Kart 7", duracion: { principal: "3.5 h", extras: "8 h", completo: "24 h" }, anio: 2011, genero: "Carreras", desarrolladora: "Nintendo EAD / Retro Studios" },
      { titulo: "Kid Icarus: Uprising", duracion: { principal: "9.5 h", extras: "14 h", completo: "26 h" }, anio: 2012, genero: "TPS / Rail Shooter", desarrolladora: "Project Sora" }
    ]
  },
  {
    consola: "PC / Windows",
    lista: [
      { titulo: "Half-Life", duracion: { principal: "11.5 h", extras: "13 h", completo: "15 h" }, anio: 1998, genero: "FPS / Ciencia Ficción", desarrolladora: "Valve" },
      { titulo: "Ship of Harkinian (Ocarina of Time)", duracion: { principal: "26.5 h", extras: "31 h", completo: "38 h" }, anio: 2022, genero: "Acción / Aventura", desarrolladora: "Harbour Masters" },
      { titulo: "Battlefield 1942", duracion: { principal: "12 h", extras: "15 h", completo: "20 h" }, anio: 2002, genero: "FPS / Bélico", desarrolladora: "DICE" },
      { titulo: "Borderlands", duracion: { principal: "22.5 h", extras: "30 h", completo: "62 h" }, anio: 2009, genero: "FPS / Looter Shooter", desarrolladora: "Gearbox Software" },
      { titulo: "Naruto Shippuden: Ultimate Ninja Storm", duracion: { principal: "10.5 h", extras: "13 h", completo: "16 h" }, anio: 2008, genero: "Lucha / Acción", desarrolladora: "CyberConnect2" },
      { titulo: "Naruto Shippuden: Ultimate Ninja Storm 2", duracion: { principal: "15 h", extras: "18 h", completo: "22 h" }, anio: 2010, genero: "Lucha / Acción", desarrolladora: "CyberConnect2" },
      { titulo: "Naruto Shippuden: Ultimate Ninja Storm 3", duracion: { principal: "11.5 h", extras: "14 h", completo: "19 h" }, anio: 2013, genero: "Lucha / Acción", desarrolladora: "CyberConnect2" },
      { titulo: "Naruto Shippuden: Ultimate Ninja Storm 4", duracion: { principal: "9 h", extras: "11 h", completo: "14 h" }, anio: 2016, genero: "Lucha / Acción", desarrolladora: "CyberConnect2" },
      { titulo: "Dragon Ball Xenoverse", duracion: { principal: "17 h", extras: "26 h", completo: "51 h" }, anio: 2015, genero: "Lucha / Action RPG", desarrolladora: "Dimps" },
      { titulo: "Dragon Ball Xenoverse 2", duracion: { principal: "19.5 h", extras: "32 h", completo: "98 h" }, anio: 2016, genero: "Lucha / Action RPG", desarrolladora: "Dimps" },
      { titulo: "Celeste", duracion: { principal: "8 h", extras: "12 h", completo: "35 h" }, anio: 2018, genero: "Plataformas", desarrolladora: "Maddy Makes Games" },
      { titulo: "Cuphead", duracion: { principal: "10.5 h", extras: "13 h", completo: "25 h" }, anio: 2017, genero: "Run and Gun / Acción", desarrolladora: "Studio MDHR" },
      { titulo: "Pariah", duracion: { principal: "6.5 h", extras: "8 h", completo: "9.5 h" }, anio: 2005, genero: "FPS", desarrolladora: "Digital Extremes" },
      { titulo: "Max Payne 1", duracion: { principal: "8 h", extras: "9 h", completo: "11 h" }, anio: 2001, genero: "TPS / Acción", desarrolladora: "Remedy Entertainment" },
      { titulo: "Medal of Honor: Allied Assault", duracion: { principal: "7.5 h", extras: "8.5 h", completo: "9.5 h" }, anio: 2002, genero: "FPS / Bélico", desarrolladora: "2015, Inc." },
      { titulo: "Beyond Good & Evil", duracion: { principal: "10 h", extras: "11.5 h", completo: "13 h" }, anio: 2003, genero: "Acción / Aventura", desarrolladora: "Ubisoft Pictures" },
      { titulo: "Doom 3", duracion: { principal: "11 h", extras: "12 h", completo: "14 h" }, anio: 2004, genero: "FPS / Survival Horror", desarrolladora: "id Software" },
      { titulo: "F.E.A.R.", duracion: { principal: "8 h", extras: "9 h", completo: "11 h" }, anio: 2005, genero: "FPS / Terror", desarrolladora: "Monolith Productions" },
      { titulo: "TES IV: Oblivion", duracion: { principal: "27.5 h", extras: "41 h", completo: "87 h" }, anio: 2006, genero: "ARPG / Mundo Abierto", desarrolladora: "Bethesda Game Studios" },
      { titulo: "Company of Heroes 1", duracion: { principal: "15.5 h", extras: "20 h", completo: "32 h" }, anio: 2006, genero: "Estrategia (RTS)", desarrolladora: "Relic Entertainment" },
      { titulo: "Hitman: Blood Money", duracion: { principal: "13 h", extras: "15 h", completo: "20 h" }, anio: 2006, genero: "Sigilo / Acción", desarrolladora: "IO Interactive" },
      { titulo: "Yakuza 0", duracion: { principal: "31.5 h", extras: "62 h", completo: "141 h" }, anio: 2015, genero: "Acción / Beat 'em up", desarrolladora: "Ryu Ga Gotoku Studio" }
,
{ titulo: "2 Ship 2 Harkinian (Majora's Mask)", duracion: { principal: "20.5 h", extras: "25 h", completo: "30 h" }, anio: 2024, genero: "Acción / Aventura", desarrolladora: "Harbour Masters" },
      { titulo: "Perfect Dark", duracion: { principal: "9.5 h", extras: "13 h", completo: "20 h" }, anio: 2000, genero: "FPS / Sigilo", desarrolladora: "Rare" },
      { titulo: "The Binding of Isaac: Rebirth", duracion: { principal: "11.5 h", extras: "50 h", completo: "426 h" }, anio: 2014, genero: "Roguelike / Puzle", desarrolladora: "Nicalis / Edmund McMillen" },
      { titulo: "Left 4 Dead 1", duracion: { principal: "6 h", extras: "9 h", completo: "43 h" }, anio: 2008, genero: "FPS / Supervivencia", desarrolladora: "Valve / Turtle Rock Studios" },
      { titulo: "Transformers: Fall of Cybertron", duracion: { principal: "8.5 h", extras: "10 h", completo: "12 h" }, anio: 2012, genero: "TPS / Acción", desarrolladora: "High Moon Studios" },
      { titulo: "PAC-MAN WORLD Re-PAC", duracion: { principal: "5 h", extras: "7 h", completo: "11 h" }, anio: 2022, genero: "Plataformas 3D", desarrolladora: "NOW Production" },
      { titulo: "Blasphemous 2", duracion: { principal: "14 h", extras: "19 h", completo: "27 h" }, anio: 2023, genero: "Metroidvania / Hack and Slash", desarrolladora: "The Game Kitchen" },
      { titulo: "Tomb Raider (2013)", duracion: { principal: "11.5 h", extras: "15 h", completo: "21 h" }, anio: 2013, genero: "Acción / Aventura", desarrolladora: "Crystal Dynamics" },
      { titulo: "Sleeping Dogs", duracion: { principal: "14.5 h", extras: "21 h", completo: "32 h" }, anio: 2012, genero: "Acción / Mundo Abierto", desarrolladora: "United Front Games" },
      { titulo: "Assassin's Creed Brotherhood", duracion: { principal: "15 h", extras: "22 h", completo: "37 h" }, anio: 2010, genero: "Acción / Sigilo", desarrolladora: "Ubisoft Montreal" },
      { titulo: "Mafia II", duracion: { principal: "12 h", extras: "14 h", completo: "26 h" }, anio: 2010, genero: "Acción / Mundo Abierto", desarrolladora: "2K Czech" },
      { titulo: "Just Cause 2", duracion: { principal: "18 h", extras: "34 h", completo: "75 h" }, anio: 2010, genero: "Acción / Mundo Abierto", desarrolladora: "Avalanche Studios" },
      { titulo: "Mirror's Edge", duracion: { principal: "6 h", extras: "7 h", completo: "9 h" }, anio: 2008, genero: "Plataformas / FPS", desarrolladora: "DICE" },
      { titulo: "Dead Space", duracion: { principal: "11 h", extras: "13 h", completo: "20 h" }, anio: 2008, genero: "Survival Horror / TPS", desarrolladora: "EA Redwood Shores" },
      { titulo: "Dead Cells", duracion: { principal: "14.5 h", extras: "29 h", completo: "90 h" }, anio: 2018, genero: "Roguelite / Metroidvania", desarrolladora: "Motion Twin" },
      { titulo: "Shovel Knight", duracion: { principal: "7 h", extras: "9 h", completo: "16 h" }, anio: 2014, genero: "Plataformas / Acción", desarrolladora: "Yacht Club Games" },
      { titulo: "Inside", duracion: { principal: "3.5 h", extras: "4 h", completo: "4.5 h" }, anio: 2016, genero: "Plataformas / Puzle", desarrolladora: "Playdead" },
      { titulo: "Call of Duty 4: Modern Warfare", duracion: { principal: "7 h", extras: "8 h", completo: "11 h" }, anio: 2007, genero: "FPS", desarrolladora: "Infinity Ward" },
      { titulo: "Deus Ex: Human Revolution", duracion: { principal: "21.5 h", extras: "31 h", completo: "49 h" }, anio: 2011, genero: "Action RPG / Sigilo", desarrolladora: "Eidos-Montréal" },
      { titulo: "Crysis", duracion: { principal: "10 h", extras: "11 h", completo: "14 h" }, anio: 2007, genero: "FPS / Ciencia Ficción", desarrolladora: "Crytek" },
      { titulo: "Animal Well", duracion: { principal: "7.5 h", extras: "13 h", completo: "20 h" }, anio: 2024, genero: "Metroidvania / Puzle", desarrolladora: "Shared Memory" },
      { titulo: "Ori and the Blind Forest: Definitive Edition", duracion: { principal: "8 h", extras: "11 h", completo: "15 h" }, anio: 2016, genero: "Metroidvania / Plataformas", desarrolladora: "Moon Studios" },
      { titulo: "Katana ZERO", duracion: { principal: "4.5 h", extras: "5.5 h", completo: "10 h" }, anio: 2019, genero: "Acción / Hack and Slash", desarrolladora: "Askiソフト" },
      { titulo: "Rayman Legends", duracion: { principal: "10 h", extras: "13.5 h", completo: "20 h" }, anio: 2013, genero: "Plataformas", desarrolladora: "Ubisoft Montpellier" },
      { titulo: "Ōkami HD", duracion: { principal: "33.5 h", extras: "43 h", completo: "64 h" }, anio: 2012, genero: "Acción / Aventura", desarrolladora: "Clover Studio / HexaDrive" },
      { titulo: "Max Payne 3", duracion: { principal: "12 h", extras: "14 h", completo: "18 h" }, anio: 2012, genero: "TPS / Acción", desarrolladora: "Rockstar Studios" },
      { titulo: "Sonic Colors: Ultimate", duracion: { principal: "4.5 h", extras: "6 h", completo: "9 h" }, anio: 2021, genero: "Plataformas", desarrolladora: "Blind Squirrel Games" },
      { titulo: "Assassin's Creed III", duracion: { principal: "16 h", extras: "27 h", completo: "54 h" }, anio: 2012, genero: "Acción / Aventura", desarrolladora: "Ubisoft Montreal" },
      { titulo: "Assassin's Creed IV: Black Flag", duracion: { principal: "23.5 h", extras: "35 h", completo: "61 h" }, anio: 2013, genero: "Acción / Mundo Abierto", desarrolladora: "Ubisoft Montreal" },
      { titulo: "TMNT: Shredder's Revenge", duracion: { principal: "2.5 h", extras: "3.5 h", completo: "7.5 h" }, anio: 2022, genero: "Beat 'em up", desarrolladora: "Tribute Games" },
      { titulo: "StarCraft II: Wings of Liberty", duracion: { principal: "15 h", extras: "18 h", completo: "26 h" }, anio: 2010, genero: "Estrategia (RTS)", desarrolladora: "Blizzard Entertainment" },
      { titulo: "Fallout: New Vegas", duracion: { principal: "27.5 h", extras: "47 h", completo: "96 h" }, anio: 2010, genero: "Action RPG / Mundo Abierto", desarrolladora: "Obsidian Entertainment" },
      { titulo: "Metro 2033", duracion: { principal: "9 h", extras: "10 h", completo: "12 h" }, anio: 2010, genero: "FPS / Survival Horror", desarrolladora: "4A Games" },
      { titulo: "Limbo", duracion: { principal: "3.5 h", extras: "4 h", completo: "5 h" }, anio: 2010, genero: "Plataformas / Puzle", desarrolladora: "Playdead" },
      { titulo: "The Thing Remastered", duracion: { principal: "7.5 h", extras: "9 h", completo: "11 h" }, anio: 2024, genero: "Survival Horror / TPS", desarrolladora: "Nightdive Studios" },
      { titulo: "GTA Vice City", duracion: { principal: "18.5 h", extras: "25 h", completo: "42 h" }, anio: 2002, genero: "Acción / Mundo Abierto", desarrolladora: "Rockstar North" },
      { titulo: "Call of Duty (Deluxe)", duracion: { principal: "6.5 h", extras: "7.5 h", completo: "9 h" }, anio: 2003, genero: "FPS", desarrolladora: "Infinity Ward" },
      { titulo: "Call of Duty: World at War", duracion: { principal: "7.5 h", extras: "9 h", completo: "12 h" }, anio: 2008, genero: "FPS", desarrolladora: "Treyarch" },
      { titulo: "Call of Duty: Modern Warfare 2", duracion: { principal: "6.5 h", extras: "7.5 h", completo: "9.5 h" }, anio: 2009, genero: "FPS", desarrolladora: "Infinity Ward" },
      { titulo: "Battlefield 3", duracion: { principal: "6 h", extras: "8 h", completo: "11 h" }, anio: 2011, genero: "FPS", desarrolladora: "DICE" },
      { titulo: "Transformers: Devastation", duracion: { principal: "6 h", extras: "7 h", completo: "10 h" }, anio: 2015, genero: "Hack and Slash / Acción", desarrolladora: "PlatinumGames" },
      { titulo: "Battlefield: Bad Company 2", duracion: { principal: "7 h", extras: "8 h", completo: "10 h" }, anio: 2010, genero: "FPS", desarrolladora: "DICE" },
      { titulo: "Amnesia: The Dark Descent", duracion: { principal: "8 h", extras: "8.5 h", completo: "10 h" }, anio: 2010, genero: "Survival Horror", desarrolladora: "Frictional Games" },
      { titulo: "Enslaved: Odyssey to the West", duracion: { principal: "9.5 h", extras: "11 h", completo: "13 h" }, anio: 2010, genero: "Acción / Aventura", desarrolladora: "Ninja Theory" },
      { titulo: "TES V: Skyrim", duracion: { principal: "34.5 h", extras: "70 h", completo: "233 h" }, anio: 2011, genero: "ARPG / Mundo Abierto", desarrolladora: "Bethesda Game Studios" },
      { titulo: "Dark Souls: Remastered", duracion: { principal: "41.5 h", extras: "60 h", completo: "91 h" }, anio: 2018, genero: "Action RPG", desarrolladora: "QLOC / FromSoftware" },
      { titulo: "L.A. Noire", duracion: { principal: "21.5 h", extras: "27 h", completo: "39 h" }, anio: 2011, genero: "Aventura / Misterio", desarrolladora: "Team Bondi" },
      { titulo: "Saints Row: The Third", duracion: { principal: "14.5 h", extras: "22 h", completo: "43 h" }, anio: 2011, genero: "Acción / Mundo Abierto", desarrolladora: "Volition" },
      { titulo: "Alice: Madness Returns", duracion: { principal: "13.5 h", extras: "15 h", completo: "18 h" }, anio: 2011, genero: "Plataformas / Acción", desarrolladora: "Spicy Horse" },
      { titulo: "The Walking Dead", duracion: { principal: "11.5 h", extras: "12 h", completo: "13 h" }, anio: 2012, genero: "Aventura Gráfica", desarrolladora: "Telltale Games" },
      { titulo: "Call of Duty: Black Ops 2", duracion: { principal: "7 h", extras: "8 h", completo: "11 h" }, anio: 2012, genero: "FPS", desarrolladora: "Treyarch" },
      { titulo: "Spec Ops: The Line", duracion: { principal: "6 h", extras: "7 h", completo: "9 h" }, anio: 2012, genero: "TPS / Acción", desarrolladora: "Yager Development" },
      { titulo: "BioShock Infinite", duracion: { principal: "11.5 h", extras: "14 h", completo: "27 h" }, anio: 2013, genero: "FPS / Ciencia Ficción", desarrolladora: "Irrational Games" },
      { titulo: "Metro: Last Light", duracion: { principal: "10 h", extras: "11 h", completo: "14 h" }, anio: 2013, genero: "FPS / Survival Horror", desarrolladora: "4A Games" },
      { titulo: "Battlefield 4", duracion: { principal: "6 h", extras: "7 h", completo: "9 h" }, anio: 2013, genero: "FPS", desarrolladora: "DICE" },
      { titulo: "Outlast", duracion: { principal: "5 h", extras: "6 h", completo: "7.5 h" }, anio: 2013, genero: "Survival Horror", desarrolladora: "Red Barrels" },
      { titulo: "The Stanley Parable", duracion: { principal: "1.5 h", extras: "3.5 h", completo: "26 h" }, anio: 2013, genero: "Aventura / Narrativo", desarrolladora: "Galactic Cafe" },
      { titulo: "Assassin's Creed 2", duracion: { principal: "19 h", extras: "25 h", completo: "36 h" }, anio: 2009, genero: "Acción / Aventura", desarrolladora: "Ubisoft Montreal" },
      { titulo: "Mega Man 3 (Legacy Collection)", duracion: { principal: "2.5 h", extras: "3 h", completo: "4 h" }, anio: 2015, genero: "Plataformas / Acción", desarrolladora: "Digital Eclipse" },
      { titulo: "Final Fantasy VI Pixel Remaster", duracion: { principal: "35 h", extras: "41 h", completo: "52 h" }, anio: 2022, genero: "JRPG", desarrolladora: "Square Enix" },
      { titulo: "Wild Guns Reloaded", duracion: { principal: "1 h", extras: "1.5 h", completo: "6 h" }, anio: 2017, genero: "Shoot 'em up / Arcade", desarrolladora: "NatsumeAtari" },
      { titulo: "PAC-MAN WORLD 2 Re-PAC", duracion: { principal: "6.5 h", extras: "8 h", completo: "12 h" }, anio: 2025, genero: "Plataformas 3D", desarrolladora: "Bandai Namco Studios" },
      { titulo: "Legacy of Kain: Soul Reaver 1 Remastered", duracion: { principal: "13.5 h", extras: "15 h", completo: "18 h" }, anio: 2024, genero: "Acción / Aventura", desarrolladora: "Aspyr / Crystal Dynamics" },
      { titulo: "Turok 2 Remastered", duracion: { principal: "12.5 h", extras: "14 h", completo: "17 h" }, anio: 2015, genero: "FPS / Acción", desarrolladora: "Nightdive Studios" },
      { titulo: "Shadow Man Remastered", duracion: { principal: "17.5 h", extras: "21 h", completo: "26 h" }, anio: 2021, genero: "Acción / Aventura", desarrolladora: "Nightdive Studios" },
      { titulo: "Silent Hill 2 Enhanced Edition", duracion: { principal: "8 h", extras: "10 h", completo: "13 h" }, anio: 2018, genero: "Survival Horror", desarrolladora: "Townfall Team" },
      { titulo: "LEGO Indiana Jones: The Original Adventures", duracion: { principal: "27 h", extras: "35 h", completo: "52 h" }, anio: 2008, genero: "Acción / Aventura", desarrolladora: "TT Games" },
      { titulo: "DMC HD Collection (DMC 1)", duracion: { principal: "6 h", extras: "8 h", completo: "14 h" }, anio: 2018, genero: "Hack and Slash", desarrolladora: "Capcom" },
      { titulo: "GTA III", duracion: { principal: "15.5 h", extras: "20 h", completo: "40 h" }, anio: 2001, genero: "Acción / Mundo Abierto", desarrolladora: "DMA Design" },
      { titulo: "The Simpsons: Hit & Run", duracion: { principal: "10 h", extras: "14 h", completo: "20 h" }, anio: 2003, genero: "Acción / Conducción", desarrolladora: "Radical Entertainment" },
      { titulo: "Manhunt 2", duracion: { principal: "6.5 h", extras: "8 h", completo: "10 h" }, anio: 2007, genero: "Sigilo / Survival Horror", desarrolladora: "Rockstar Vienna" },
      { titulo: "Sonic Adventure 2", duracion: { principal: "9.5 h", extras: "13 h", completo: "20 h" }, anio: 2012, genero: "Plataformas 3D", desarrolladora: "Sonic Team" },
      { titulo: "Prince of Persia: The Sands of Time", duracion: { principal: "9 h", extras: "10 h", completo: "12 h" }, anio: 2003, genero: "Acción / Plataformas", desarrolladora: "Ubisoft Montreal" },
      { titulo: "Bayonetta", duracion: { principal: "11.5 h", extras: "14 h", completo: "23 h" }, anio: 2017, genero: "Hack and Slash", desarrolladora: "PlatinumGames" },
      { titulo: "Vanquish", duracion: { principal: "6 h", extras: "8 h", completo: "12 h" }, anio: 2017, genero: "TPS / Acción", desarrolladora: "PlatinumGames" },
      { titulo: "The Wonderful 101", duracion: { principal: "18 h", extras: "23 h", completo: "35 h" }, anio: 2020, genero: "Acción / Hack and Slash", desarrolladora: "PlatinumGames" },
      { titulo: "Dragon's Dogma: Dark Arisen", duracion: { principal: "32.5 h", extras: "54 h", completo: "116 h" }, anio: 2016, genero: "Action RPG", desarrolladora: "Capcom" },
      { titulo: "Sea of Stars", duracion: { principal: "30.5 h", extras: "39 h", completo: "49 h" }, anio: 2023, genero: "JRPG", desarrolladora: "Sabotage Studio" },
      { titulo: "Super Meat Boy", duracion: { principal: "10 h", extras: "16 h", completo: "35 h" }, anio: 2010, genero: "Plataformas", desarrolladora: "Team Meat" },
      { titulo: "Quake Enhanced Edition", duracion: { principal: "5.5 h", extras: "7 h", completo: "10 h" }, anio: 2021, genero: "FPS", desarrolladora: "Nightdive Studios / id Software" },
      { titulo: "Spongebob Battle for Bikini Bottom Rehydrated", duracion: { principal: "7.5 h", extras: "10 h", completo: "15 h" }, anio: 2020, genero: "Plataformas 3D", desarrolladora: "Purple Lamp Studios" },
      { titulo: "Half-Life 2", duracion: { principal: "13 h", extras: "15 h", completo: "19 h" }, anio: 2004, genero: "FPS / Ciencia Ficción", desarrolladora: "Valve" },
      { titulo: "Portal 2", duracion: { principal: "8.5 h", extras: "10 h", completo: "21 h" }, anio: 2011, genero: "Puzle / FPS", desarrolladora: "Valve" },
      { titulo: "Batman: Arkham City", duracion: { principal: "12.5 h", extras: "22 h", completo: "45 h" }, anio: 2011, genero: "Acción / Aventura", desarrolladora: "Rocksteady Studios" },
      { titulo: "Alien: Isolation", duracion: { principal: "18.5 h", extras: "22 h", completo: "33 h" }, anio: 2014, genero: "Survival Horror / Sigilo", desarrolladora: "Creative Assembly" },
      { titulo: "Outlast 2", duracion: { principal: "7.5 h", extras: "9 h", completo: "11 h" }, anio: 2017, genero: "Survival Horror", desarrolladora: "Red Barrels" },
      { titulo: "Darksiders", duracion: { principal: "15 h", extras: "18 h", completo: "23 h" }, anio: 2010, genero: "Hack and Slash / Aventura", desarrolladora: "Vigil Games" },
      { titulo: "Kingdoms of Amalur: Reckoning", duracion: { principal: "31.5 h", extras: "52 h", completo: "92 h" }, anio: 2012, genero: "Action RPG", desarrolladora: "38 Studios / Big Huge Games" },
      { titulo: "Bully: Scholarship Edition", duracion: { principal: "13 h", extras: "19 h", completo: "28 h" }, anio: 2008, genero: "Acción / Mundo Abierto", desarrolladora: "Mad Doc Software / Rockstar" },
      { titulo: "Prototype", duracion: { principal: "15.5 h", extras: "19 h", completo: "27 h" }, anio: 2009, genero: "Acción / Mundo Abierto", desarrolladora: "Radical Entertainment" },
      { titulo: "Mark of the Ninja: Remastered", duracion: { principal: "7.5 h", extras: "9 h", completo: "14 h" }, anio: 2018, genero: "Sigilo / Plataformas", desarrolladora: "Klei Entertainment" },
      { titulo: "The Wolf Among Us", duracion: { principal: "6.5 h", extras: "7 h", completo: "8 h" }, anio: 2013, genero: "Aventura Gráfica", desarrolladora: "Telltale Games" },
      { titulo: "Bastion", duracion: { principal: "6 h", extras: "7 h", completo: "11 h" }, anio: 2011, genero: "Action RPG", desarrolladora: "Supergiant Games" },
      { titulo: "Remember Me", duracion: { principal: "9 h", extras: "10 h", completo: "12 h" }, anio: 2013, genero: "Acción / Aventura", desarrolladora: "DONTNOD Entertainment" },
      { titulo: "Left 4 Dead 2", duracion: { principal: "8 h", extras: "13 h", completo: "62 h" }, anio: 2009, genero: "FPS / Supervivencia", desarrolladora: "Valve" },
      { titulo: "Ninja Gaiden Ragebound", duracion: { principal: "3 h", extras: "4 h", completo: "5.5 h" }, anio: 2025, genero: "Acción / Hack and Slash", desarrolladora: "Koei Tecmo" },
      { titulo: "Far Cry 2", duracion: { principal: "16.5 h", extras: "22 h", completo: "35 h" }, anio: 2008, genero: "FPS / Mundo Abierto", desarrolladora: "Ubisoft Montreal" },
      { titulo: "Driver: San Francisco", duracion: { principal: "10.5 h", extras: "15 h", completo: "27 h" }, anio: 2011, genero: "Acción / Conducción", desarrolladora: "Ubisoft Reflections" },
      { titulo: "Broforce", duracion: { principal: "4 h", extras: "6 h", completo: "12 h" }, anio: 2015, genero: "Run and Gun / Acción", desarrolladora: "Free Lives" },
      { titulo: "Sonic Adventure DX", duracion: { principal: "4.5 h", extras: "6 h", completo: "9 h" }, anio: 2004, genero: "Plataformas 3D", desarrolladora: "Sonic Team" },
      { titulo: "JoJo's Bizarre Adventure: All-Star Battle R", duracion: { principal: "5.5 h", extras: "10 h", completo: "27 h" }, anio: 2022, genero: "Lucha", desarrolladora: "CyberConnect2" },
      { titulo: "Binary Domain", duracion: { principal: "9 h", extras: "11 h", completo: "14 h" }, anio: 2012, genero: "TPS / Acción", desarrolladora: "Devil's Details / Ryu Ga Gotoku Studio" },
      { titulo: "LEGO Marvel Super Heroes", duracion: { principal: "42.5 h", extras: "55 h", completo: "76 h" }, anio: 2013, genero: "Acción / Aventura", desarrolladora: "TT Games" },
      { titulo: "LEGO Marvel Super Heroes 2", duracion: { principal: "57.5 h", extras: "73 h", completo: "96 h" }, anio: 2017, genero: "Acción / Aventura", desarrolladora: "TT Games" },
      { titulo: "GTA San Andreas (+ Mods)", duracion: { principal: "30.5 h", extras: "47 h", completo: "90 h" }, anio: 2004, genero: "Acción / Mundo Abierto", desarrolladora: "Rockstar North" },
      { titulo: "Batman: Arkham Asylum", duracion: { principal: "11.5 h", extras: "16 h", completo: "25 h" }, anio: 2009, genero: "Acción / Aventura", desarrolladora: "Rocksteady Studios" }
    ]
  }
];
